//
// Generated by Bluespec Compiler, version 2015.09.beta2 (build 34689, 2015-09-07)
//
// On Mon Sep 11 20:06:28 EDT 2017
//
//
// Ports:
// Name                         I/O  size props
// RDY_gatherInPort_putFlit       O     1
// gatherOutPort_getFlit          O    91
// RDY_gatherOutPort_getFlit      O     1
// RDY_scatterInPort_putFlit      O     1
// scatterOutPort_getFlit         O    91
// RDY_scatterOutPort_getFlit     O     1
// RDY_interPEInPort_0_putFlit    O     1
// RDY_interPEInPort_1_putFlit    O     1
// RDY_interPEInPort_2_putFlit    O     1
// interPEOutPort_0_getFlit       O    91
// RDY_interPEOutPort_0_getFlit   O     1
// interPEOutPort_1_getFlit       O    91
// RDY_interPEOutPort_1_getFlit   O     1
// interPEOutPort_2_getFlit       O    91
// RDY_interPEOutPort_2_getFlit   O     1
// RDY_initialize                 O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// gatherInPort_putFlit_flit      I    91
// scatterInPort_putFlit_flit     I    91
// interPEInPort_0_putFlit_flit   I    91
// interPEInPort_1_putFlit_flit   I    91
// interPEInPort_2_putFlit_flit   I    91
// initialize_initPEID            I     7 reg
// EN_gatherInPort_putFlit        I     1
// EN_scatterInPort_putFlit       I     1
// EN_interPEInPort_0_putFlit     I     1
// EN_interPEInPort_1_putFlit     I     1
// EN_interPEInPort_2_putFlit     I     1
// EN_initialize                  I     1
// EN_gatherOutPort_getFlit       I     1
// EN_scatterOutPort_getFlit      I     1
// EN_interPEOutPort_0_getFlit    I     1
// EN_interPEOutPort_1_getFlit    I     1
// EN_interPEOutPort_2_getFlit    I     1
//
// Combinational paths from inputs to outputs:
//   (gatherInPort_putFlit_flit,
//    EN_gatherInPort_putFlit) -> gatherOutPort_getFlit
//   (scatterInPort_putFlit_flit,
//    interPEInPort_0_putFlit_flit,
//    interPEInPort_1_putFlit_flit,
//    EN_scatterInPort_putFlit,
//    EN_interPEInPort_0_putFlit,
//    EN_interPEInPort_1_putFlit) -> scatterOutPort_getFlit
//   (interPEInPort_0_putFlit_flit,
//    interPEInPort_1_putFlit_flit,
//    EN_scatterInPort_putFlit,
//    EN_interPEInPort_0_putFlit,
//    EN_interPEInPort_1_putFlit) -> RDY_scatterOutPort_getFlit
//   (interPEInPort_0_putFlit_flit,
//    interPEInPort_2_putFlit_flit,
//    EN_interPEInPort_0_putFlit,
//    EN_interPEInPort_2_putFlit) -> RDY_interPEOutPort_0_getFlit
//   (interPEInPort_0_putFlit_flit,
//    interPEInPort_1_putFlit_flit,
//    EN_interPEInPort_0_putFlit,
//    EN_interPEInPort_1_putFlit) -> RDY_interPEOutPort_2_getFlit
//   (interPEInPort_0_putFlit_flit,
//    interPEInPort_2_putFlit_flit,
//    EN_interPEInPort_0_putFlit,
//    EN_interPEInPort_2_putFlit) -> interPEOutPort_0_getFlit
//   (interPEInPort_0_putFlit_flit,
//    interPEInPort_1_putFlit_flit,
//    EN_interPEInPort_0_putFlit,
//    EN_interPEInPort_1_putFlit) -> interPEOutPort_2_getFlit
//   (interPEInPort_1_putFlit_flit,
//    interPEInPort_2_putFlit_flit,
//    EN_interPEInPort_1_putFlit,
//    EN_interPEInPort_2_putFlit) -> RDY_interPEOutPort_1_getFlit
//   (interPEInPort_1_putFlit_flit,
//    interPEInPort_2_putFlit_flit,
//    EN_interPEInPort_1_putFlit,
//    EN_interPEInPort_2_putFlit) -> interPEOutPort_1_getFlit
//   EN_gatherInPort_putFlit -> RDY_gatherOutPort_getFlit
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkBottomSwitch(CLK,
		      RST_N,

		      gatherInPort_putFlit_flit,
		      EN_gatherInPort_putFlit,
		      RDY_gatherInPort_putFlit,

		      EN_gatherOutPort_getFlit,
		      gatherOutPort_getFlit,
		      RDY_gatherOutPort_getFlit,

		      scatterInPort_putFlit_flit,
		      EN_scatterInPort_putFlit,
		      RDY_scatterInPort_putFlit,

		      EN_scatterOutPort_getFlit,
		      scatterOutPort_getFlit,
		      RDY_scatterOutPort_getFlit,

		      interPEInPort_0_putFlit_flit,
		      EN_interPEInPort_0_putFlit,
		      RDY_interPEInPort_0_putFlit,

		      interPEInPort_1_putFlit_flit,
		      EN_interPEInPort_1_putFlit,
		      RDY_interPEInPort_1_putFlit,

		      interPEInPort_2_putFlit_flit,
		      EN_interPEInPort_2_putFlit,
		      RDY_interPEInPort_2_putFlit,

		      EN_interPEOutPort_0_getFlit,
		      interPEOutPort_0_getFlit,
		      RDY_interPEOutPort_0_getFlit,

		      EN_interPEOutPort_1_getFlit,
		      interPEOutPort_1_getFlit,
		      RDY_interPEOutPort_1_getFlit,

		      EN_interPEOutPort_2_getFlit,
		      interPEOutPort_2_getFlit,
		      RDY_interPEOutPort_2_getFlit,

		      initialize_initPEID,
		      EN_initialize,
		      RDY_initialize);
  input  CLK;
  input  RST_N;

  // action method gatherInPort_putFlit
  input  [90 : 0] gatherInPort_putFlit_flit;
  input  EN_gatherInPort_putFlit;
  output RDY_gatherInPort_putFlit;

  // actionvalue method gatherOutPort_getFlit
  input  EN_gatherOutPort_getFlit;
  output [90 : 0] gatherOutPort_getFlit;
  output RDY_gatherOutPort_getFlit;

  // action method scatterInPort_putFlit
  input  [90 : 0] scatterInPort_putFlit_flit;
  input  EN_scatterInPort_putFlit;
  output RDY_scatterInPort_putFlit;

  // actionvalue method scatterOutPort_getFlit
  input  EN_scatterOutPort_getFlit;
  output [90 : 0] scatterOutPort_getFlit;
  output RDY_scatterOutPort_getFlit;

  // action method interPEInPort_0_putFlit
  input  [90 : 0] interPEInPort_0_putFlit_flit;
  input  EN_interPEInPort_0_putFlit;
  output RDY_interPEInPort_0_putFlit;

  // action method interPEInPort_1_putFlit
  input  [90 : 0] interPEInPort_1_putFlit_flit;
  input  EN_interPEInPort_1_putFlit;
  output RDY_interPEInPort_1_putFlit;

  // action method interPEInPort_2_putFlit
  input  [90 : 0] interPEInPort_2_putFlit_flit;
  input  EN_interPEInPort_2_putFlit;
  output RDY_interPEInPort_2_putFlit;

  // actionvalue method interPEOutPort_0_getFlit
  input  EN_interPEOutPort_0_getFlit;
  output [90 : 0] interPEOutPort_0_getFlit;
  output RDY_interPEOutPort_0_getFlit;

  // actionvalue method interPEOutPort_1_getFlit
  input  EN_interPEOutPort_1_getFlit;
  output [90 : 0] interPEOutPort_1_getFlit;
  output RDY_interPEOutPort_1_getFlit;

  // actionvalue method interPEOutPort_2_getFlit
  input  EN_interPEOutPort_2_getFlit;
  output [90 : 0] interPEOutPort_2_getFlit;
  output RDY_interPEOutPort_2_getFlit;

  // action method initialize
  input  [6 : 0] initialize_initPEID;
  input  EN_initialize;
  output RDY_initialize;

  // signals for module outputs
  wire [90 : 0] gatherOutPort_getFlit,
		interPEOutPort_0_getFlit,
		interPEOutPort_1_getFlit,
		interPEOutPort_2_getFlit,
		scatterOutPort_getFlit;
  wire RDY_gatherInPort_putFlit,
       RDY_gatherOutPort_getFlit,
       RDY_initialize,
       RDY_interPEInPort_0_putFlit,
       RDY_interPEInPort_1_putFlit,
       RDY_interPEInPort_2_putFlit,
       RDY_interPEOutPort_0_getFlit,
       RDY_interPEOutPort_1_getFlit,
       RDY_interPEOutPort_2_getFlit,
       RDY_scatterInPort_putFlit,
       RDY_scatterOutPort_getFlit;

  // inlined wires
  wire [90 : 0] localFlitOutFifos_0_data_0_lat_0$wget,
		localFlitOutFifos_1_data_0_lat_0$wget,
		localFlitOutFifos_2_data_0_lat_0$wget;
  wire [1 : 0] gatherFlitFifo_deqP_lat_0$wget,
	       gatherFlitFifo_enqP_lat_0$wget,
	       scatterFlitFifo_deqP_lat_0$wget,
	       scatterFlitFifo_enqP_lat_0$wget;
  wire deqBits_2_lat_0$whas,
       deqBits_2_lat_1$whas,
       localFlitInFifos_0_deqP_lat_0$whas,
       localFlitInFifos_1_deqP_lat_0$whas,
       localFlitInFifos_2_deqP_lat_0$whas,
       localFlitOutFifos_0_data_0_lat_0$whas,
       localFlitOutFifos_1_data_0_lat_0$whas,
       localFlitOutFifos_2_data_0_lat_0$whas,
       localFlitOutFifos_2_deqP_lat_0$whas;

  // register controlSignal
  reg [1 : 0] controlSignal;
  wire [1 : 0] controlSignal$D_IN;
  wire controlSignal$EN;

  // register deqBits_0_dummy2_0
  reg deqBits_0_dummy2_0;
  wire deqBits_0_dummy2_0$D_IN, deqBits_0_dummy2_0$EN;

  // register deqBits_0_dummy2_1
  reg deqBits_0_dummy2_1;
  wire deqBits_0_dummy2_1$D_IN, deqBits_0_dummy2_1$EN;

  // register deqBits_0_dummy2_2
  reg deqBits_0_dummy2_2;
  wire deqBits_0_dummy2_2$D_IN, deqBits_0_dummy2_2$EN;

  // register deqBits_0_rl
  reg deqBits_0_rl;
  wire deqBits_0_rl$D_IN, deqBits_0_rl$EN;

  // register deqBits_1_dummy2_0
  reg deqBits_1_dummy2_0;
  wire deqBits_1_dummy2_0$D_IN, deqBits_1_dummy2_0$EN;

  // register deqBits_1_dummy2_1
  reg deqBits_1_dummy2_1;
  wire deqBits_1_dummy2_1$D_IN, deqBits_1_dummy2_1$EN;

  // register deqBits_1_dummy2_2
  reg deqBits_1_dummy2_2;
  wire deqBits_1_dummy2_2$D_IN, deqBits_1_dummy2_2$EN;

  // register deqBits_1_rl
  reg deqBits_1_rl;
  wire deqBits_1_rl$D_IN, deqBits_1_rl$EN;

  // register deqBits_2_dummy2_0
  reg deqBits_2_dummy2_0;
  wire deqBits_2_dummy2_0$D_IN, deqBits_2_dummy2_0$EN;

  // register deqBits_2_dummy2_1
  reg deqBits_2_dummy2_1;
  wire deqBits_2_dummy2_1$D_IN, deqBits_2_dummy2_1$EN;

  // register deqBits_2_dummy2_2
  reg deqBits_2_dummy2_2;
  wire deqBits_2_dummy2_2$D_IN, deqBits_2_dummy2_2$EN;

  // register deqBits_2_rl
  reg deqBits_2_rl;
  wire deqBits_2_rl$D_IN, deqBits_2_rl$EN;

  // register gatherFlitFifo_data_0_dummy2_0
  reg gatherFlitFifo_data_0_dummy2_0;
  wire gatherFlitFifo_data_0_dummy2_0$D_IN, gatherFlitFifo_data_0_dummy2_0$EN;

  // register gatherFlitFifo_data_0_dummy2_1
  reg gatherFlitFifo_data_0_dummy2_1;
  wire gatherFlitFifo_data_0_dummy2_1$D_IN, gatherFlitFifo_data_0_dummy2_1$EN;

  // register gatherFlitFifo_data_0_rl
  reg [90 : 0] gatherFlitFifo_data_0_rl;
  wire [90 : 0] gatherFlitFifo_data_0_rl$D_IN;
  wire gatherFlitFifo_data_0_rl$EN;

  // register gatherFlitFifo_deqP_dummy2_0
  reg gatherFlitFifo_deqP_dummy2_0;
  wire gatherFlitFifo_deqP_dummy2_0$D_IN, gatherFlitFifo_deqP_dummy2_0$EN;

  // register gatherFlitFifo_deqP_dummy2_1
  reg gatherFlitFifo_deqP_dummy2_1;
  wire gatherFlitFifo_deqP_dummy2_1$D_IN, gatherFlitFifo_deqP_dummy2_1$EN;

  // register gatherFlitFifo_deqP_rl
  reg [1 : 0] gatherFlitFifo_deqP_rl;
  wire [1 : 0] gatherFlitFifo_deqP_rl$D_IN;
  wire gatherFlitFifo_deqP_rl$EN;

  // register gatherFlitFifo_enqP_dummy2_0
  reg gatherFlitFifo_enqP_dummy2_0;
  wire gatherFlitFifo_enqP_dummy2_0$D_IN, gatherFlitFifo_enqP_dummy2_0$EN;

  // register gatherFlitFifo_enqP_dummy2_1
  reg gatherFlitFifo_enqP_dummy2_1;
  wire gatherFlitFifo_enqP_dummy2_1$D_IN, gatherFlitFifo_enqP_dummy2_1$EN;

  // register gatherFlitFifo_enqP_rl
  reg [1 : 0] gatherFlitFifo_enqP_rl;
  wire [1 : 0] gatherFlitFifo_enqP_rl$D_IN;
  wire gatherFlitFifo_enqP_rl$EN;

  // register inited
  reg inited;
  wire inited$D_IN, inited$EN;

  // register localFlitInFifos_0_data_0_dummy2_0
  reg localFlitInFifos_0_data_0_dummy2_0;
  wire localFlitInFifos_0_data_0_dummy2_0$D_IN,
       localFlitInFifos_0_data_0_dummy2_0$EN;

  // register localFlitInFifos_0_data_0_dummy2_1
  reg localFlitInFifos_0_data_0_dummy2_1;
  wire localFlitInFifos_0_data_0_dummy2_1$D_IN,
       localFlitInFifos_0_data_0_dummy2_1$EN;

  // register localFlitInFifos_0_data_0_rl
  reg [90 : 0] localFlitInFifos_0_data_0_rl;
  wire [90 : 0] localFlitInFifos_0_data_0_rl$D_IN;
  wire localFlitInFifos_0_data_0_rl$EN;

  // register localFlitInFifos_0_deqP_dummy2_0
  reg localFlitInFifos_0_deqP_dummy2_0;
  wire localFlitInFifos_0_deqP_dummy2_0$D_IN,
       localFlitInFifos_0_deqP_dummy2_0$EN;

  // register localFlitInFifos_0_deqP_dummy2_1
  reg localFlitInFifos_0_deqP_dummy2_1;
  wire localFlitInFifos_0_deqP_dummy2_1$D_IN,
       localFlitInFifos_0_deqP_dummy2_1$EN;

  // register localFlitInFifos_0_deqP_rl
  reg [1 : 0] localFlitInFifos_0_deqP_rl;
  wire [1 : 0] localFlitInFifos_0_deqP_rl$D_IN;
  wire localFlitInFifos_0_deqP_rl$EN;

  // register localFlitInFifos_0_enqP_dummy2_0
  reg localFlitInFifos_0_enqP_dummy2_0;
  wire localFlitInFifos_0_enqP_dummy2_0$D_IN,
       localFlitInFifos_0_enqP_dummy2_0$EN;

  // register localFlitInFifos_0_enqP_dummy2_1
  reg localFlitInFifos_0_enqP_dummy2_1;
  wire localFlitInFifos_0_enqP_dummy2_1$D_IN,
       localFlitInFifos_0_enqP_dummy2_1$EN;

  // register localFlitInFifos_0_enqP_rl
  reg [1 : 0] localFlitInFifos_0_enqP_rl;
  wire [1 : 0] localFlitInFifos_0_enqP_rl$D_IN;
  wire localFlitInFifos_0_enqP_rl$EN;

  // register localFlitInFifos_1_data_0_dummy2_0
  reg localFlitInFifos_1_data_0_dummy2_0;
  wire localFlitInFifos_1_data_0_dummy2_0$D_IN,
       localFlitInFifos_1_data_0_dummy2_0$EN;

  // register localFlitInFifos_1_data_0_dummy2_1
  reg localFlitInFifos_1_data_0_dummy2_1;
  wire localFlitInFifos_1_data_0_dummy2_1$D_IN,
       localFlitInFifos_1_data_0_dummy2_1$EN;

  // register localFlitInFifos_1_data_0_rl
  reg [90 : 0] localFlitInFifos_1_data_0_rl;
  wire [90 : 0] localFlitInFifos_1_data_0_rl$D_IN;
  wire localFlitInFifos_1_data_0_rl$EN;

  // register localFlitInFifos_1_deqP_dummy2_0
  reg localFlitInFifos_1_deqP_dummy2_0;
  wire localFlitInFifos_1_deqP_dummy2_0$D_IN,
       localFlitInFifos_1_deqP_dummy2_0$EN;

  // register localFlitInFifos_1_deqP_dummy2_1
  reg localFlitInFifos_1_deqP_dummy2_1;
  wire localFlitInFifos_1_deqP_dummy2_1$D_IN,
       localFlitInFifos_1_deqP_dummy2_1$EN;

  // register localFlitInFifos_1_deqP_rl
  reg [1 : 0] localFlitInFifos_1_deqP_rl;
  wire [1 : 0] localFlitInFifos_1_deqP_rl$D_IN;
  wire localFlitInFifos_1_deqP_rl$EN;

  // register localFlitInFifos_1_enqP_dummy2_0
  reg localFlitInFifos_1_enqP_dummy2_0;
  wire localFlitInFifos_1_enqP_dummy2_0$D_IN,
       localFlitInFifos_1_enqP_dummy2_0$EN;

  // register localFlitInFifos_1_enqP_dummy2_1
  reg localFlitInFifos_1_enqP_dummy2_1;
  wire localFlitInFifos_1_enqP_dummy2_1$D_IN,
       localFlitInFifos_1_enqP_dummy2_1$EN;

  // register localFlitInFifos_1_enqP_rl
  reg [1 : 0] localFlitInFifos_1_enqP_rl;
  wire [1 : 0] localFlitInFifos_1_enqP_rl$D_IN;
  wire localFlitInFifos_1_enqP_rl$EN;

  // register localFlitInFifos_2_data_0_dummy2_0
  reg localFlitInFifos_2_data_0_dummy2_0;
  wire localFlitInFifos_2_data_0_dummy2_0$D_IN,
       localFlitInFifos_2_data_0_dummy2_0$EN;

  // register localFlitInFifos_2_data_0_dummy2_1
  reg localFlitInFifos_2_data_0_dummy2_1;
  wire localFlitInFifos_2_data_0_dummy2_1$D_IN,
       localFlitInFifos_2_data_0_dummy2_1$EN;

  // register localFlitInFifos_2_data_0_rl
  reg [90 : 0] localFlitInFifos_2_data_0_rl;
  wire [90 : 0] localFlitInFifos_2_data_0_rl$D_IN;
  wire localFlitInFifos_2_data_0_rl$EN;

  // register localFlitInFifos_2_deqP_dummy2_0
  reg localFlitInFifos_2_deqP_dummy2_0;
  wire localFlitInFifos_2_deqP_dummy2_0$D_IN,
       localFlitInFifos_2_deqP_dummy2_0$EN;

  // register localFlitInFifos_2_deqP_dummy2_1
  reg localFlitInFifos_2_deqP_dummy2_1;
  wire localFlitInFifos_2_deqP_dummy2_1$D_IN,
       localFlitInFifos_2_deqP_dummy2_1$EN;

  // register localFlitInFifos_2_deqP_rl
  reg [1 : 0] localFlitInFifos_2_deqP_rl;
  wire [1 : 0] localFlitInFifos_2_deqP_rl$D_IN;
  wire localFlitInFifos_2_deqP_rl$EN;

  // register localFlitInFifos_2_enqP_dummy2_0
  reg localFlitInFifos_2_enqP_dummy2_0;
  wire localFlitInFifos_2_enqP_dummy2_0$D_IN,
       localFlitInFifos_2_enqP_dummy2_0$EN;

  // register localFlitInFifos_2_enqP_dummy2_1
  reg localFlitInFifos_2_enqP_dummy2_1;
  wire localFlitInFifos_2_enqP_dummy2_1$D_IN,
       localFlitInFifos_2_enqP_dummy2_1$EN;

  // register localFlitInFifos_2_enqP_rl
  reg [1 : 0] localFlitInFifos_2_enqP_rl;
  wire [1 : 0] localFlitInFifos_2_enqP_rl$D_IN;
  wire localFlitInFifos_2_enqP_rl$EN;

  // register localFlitOutFifos_0_data_0_dummy2_0
  reg localFlitOutFifos_0_data_0_dummy2_0;
  wire localFlitOutFifos_0_data_0_dummy2_0$D_IN,
       localFlitOutFifos_0_data_0_dummy2_0$EN;

  // register localFlitOutFifos_0_data_0_dummy2_1
  reg localFlitOutFifos_0_data_0_dummy2_1;
  wire localFlitOutFifos_0_data_0_dummy2_1$D_IN,
       localFlitOutFifos_0_data_0_dummy2_1$EN;

  // register localFlitOutFifos_0_data_0_rl
  reg [90 : 0] localFlitOutFifos_0_data_0_rl;
  wire [90 : 0] localFlitOutFifos_0_data_0_rl$D_IN;
  wire localFlitOutFifos_0_data_0_rl$EN;

  // register localFlitOutFifos_0_deqP_dummy2_0
  reg localFlitOutFifos_0_deqP_dummy2_0;
  wire localFlitOutFifos_0_deqP_dummy2_0$D_IN,
       localFlitOutFifos_0_deqP_dummy2_0$EN;

  // register localFlitOutFifos_0_deqP_dummy2_1
  reg localFlitOutFifos_0_deqP_dummy2_1;
  wire localFlitOutFifos_0_deqP_dummy2_1$D_IN,
       localFlitOutFifos_0_deqP_dummy2_1$EN;

  // register localFlitOutFifos_0_deqP_rl
  reg [1 : 0] localFlitOutFifos_0_deqP_rl;
  wire [1 : 0] localFlitOutFifos_0_deqP_rl$D_IN;
  wire localFlitOutFifos_0_deqP_rl$EN;

  // register localFlitOutFifos_0_enqP_dummy2_0
  reg localFlitOutFifos_0_enqP_dummy2_0;
  wire localFlitOutFifos_0_enqP_dummy2_0$D_IN,
       localFlitOutFifos_0_enqP_dummy2_0$EN;

  // register localFlitOutFifos_0_enqP_dummy2_1
  reg localFlitOutFifos_0_enqP_dummy2_1;
  wire localFlitOutFifos_0_enqP_dummy2_1$D_IN,
       localFlitOutFifos_0_enqP_dummy2_1$EN;

  // register localFlitOutFifos_0_enqP_rl
  reg [1 : 0] localFlitOutFifos_0_enqP_rl;
  wire [1 : 0] localFlitOutFifos_0_enqP_rl$D_IN;
  wire localFlitOutFifos_0_enqP_rl$EN;

  // register localFlitOutFifos_1_data_0_dummy2_0
  reg localFlitOutFifos_1_data_0_dummy2_0;
  wire localFlitOutFifos_1_data_0_dummy2_0$D_IN,
       localFlitOutFifos_1_data_0_dummy2_0$EN;

  // register localFlitOutFifos_1_data_0_dummy2_1
  reg localFlitOutFifos_1_data_0_dummy2_1;
  wire localFlitOutFifos_1_data_0_dummy2_1$D_IN,
       localFlitOutFifos_1_data_0_dummy2_1$EN;

  // register localFlitOutFifos_1_data_0_rl
  reg [90 : 0] localFlitOutFifos_1_data_0_rl;
  wire [90 : 0] localFlitOutFifos_1_data_0_rl$D_IN;
  wire localFlitOutFifos_1_data_0_rl$EN;

  // register localFlitOutFifos_1_deqP_dummy2_0
  reg localFlitOutFifos_1_deqP_dummy2_0;
  wire localFlitOutFifos_1_deqP_dummy2_0$D_IN,
       localFlitOutFifos_1_deqP_dummy2_0$EN;

  // register localFlitOutFifos_1_deqP_dummy2_1
  reg localFlitOutFifos_1_deqP_dummy2_1;
  wire localFlitOutFifos_1_deqP_dummy2_1$D_IN,
       localFlitOutFifos_1_deqP_dummy2_1$EN;

  // register localFlitOutFifos_1_deqP_rl
  reg [1 : 0] localFlitOutFifos_1_deqP_rl;
  wire [1 : 0] localFlitOutFifos_1_deqP_rl$D_IN;
  wire localFlitOutFifos_1_deqP_rl$EN;

  // register localFlitOutFifos_1_enqP_dummy2_0
  reg localFlitOutFifos_1_enqP_dummy2_0;
  wire localFlitOutFifos_1_enqP_dummy2_0$D_IN,
       localFlitOutFifos_1_enqP_dummy2_0$EN;

  // register localFlitOutFifos_1_enqP_dummy2_1
  reg localFlitOutFifos_1_enqP_dummy2_1;
  wire localFlitOutFifos_1_enqP_dummy2_1$D_IN,
       localFlitOutFifos_1_enqP_dummy2_1$EN;

  // register localFlitOutFifos_1_enqP_rl
  reg [1 : 0] localFlitOutFifos_1_enqP_rl;
  wire [1 : 0] localFlitOutFifos_1_enqP_rl$D_IN;
  wire localFlitOutFifos_1_enqP_rl$EN;

  // register localFlitOutFifos_2_data_0_dummy2_0
  reg localFlitOutFifos_2_data_0_dummy2_0;
  wire localFlitOutFifos_2_data_0_dummy2_0$D_IN,
       localFlitOutFifos_2_data_0_dummy2_0$EN;

  // register localFlitOutFifos_2_data_0_dummy2_1
  reg localFlitOutFifos_2_data_0_dummy2_1;
  wire localFlitOutFifos_2_data_0_dummy2_1$D_IN,
       localFlitOutFifos_2_data_0_dummy2_1$EN;

  // register localFlitOutFifos_2_data_0_rl
  reg [90 : 0] localFlitOutFifos_2_data_0_rl;
  wire [90 : 0] localFlitOutFifos_2_data_0_rl$D_IN;
  wire localFlitOutFifos_2_data_0_rl$EN;

  // register localFlitOutFifos_2_deqP_dummy2_0
  reg localFlitOutFifos_2_deqP_dummy2_0;
  wire localFlitOutFifos_2_deqP_dummy2_0$D_IN,
       localFlitOutFifos_2_deqP_dummy2_0$EN;

  // register localFlitOutFifos_2_deqP_dummy2_1
  reg localFlitOutFifos_2_deqP_dummy2_1;
  wire localFlitOutFifos_2_deqP_dummy2_1$D_IN,
       localFlitOutFifos_2_deqP_dummy2_1$EN;

  // register localFlitOutFifos_2_deqP_rl
  reg [1 : 0] localFlitOutFifos_2_deqP_rl;
  wire [1 : 0] localFlitOutFifos_2_deqP_rl$D_IN;
  wire localFlitOutFifos_2_deqP_rl$EN;

  // register localFlitOutFifos_2_enqP_dummy2_0
  reg localFlitOutFifos_2_enqP_dummy2_0;
  wire localFlitOutFifos_2_enqP_dummy2_0$D_IN,
       localFlitOutFifos_2_enqP_dummy2_0$EN;

  // register localFlitOutFifos_2_enqP_dummy2_1
  reg localFlitOutFifos_2_enqP_dummy2_1;
  wire localFlitOutFifos_2_enqP_dummy2_1$D_IN,
       localFlitOutFifos_2_enqP_dummy2_1$EN;

  // register localFlitOutFifos_2_enqP_rl
  reg [1 : 0] localFlitOutFifos_2_enqP_rl;
  wire [1 : 0] localFlitOutFifos_2_enqP_rl$D_IN;
  wire localFlitOutFifos_2_enqP_rl$EN;

  // register localFlitToHost_data_0_dummy2_0
  reg localFlitToHost_data_0_dummy2_0;
  wire localFlitToHost_data_0_dummy2_0$D_IN,
       localFlitToHost_data_0_dummy2_0$EN;

  // register localFlitToHost_data_0_dummy2_1
  reg localFlitToHost_data_0_dummy2_1;
  wire localFlitToHost_data_0_dummy2_1$D_IN,
       localFlitToHost_data_0_dummy2_1$EN;

  // register localFlitToHost_data_0_rl
  reg [90 : 0] localFlitToHost_data_0_rl;
  wire [90 : 0] localFlitToHost_data_0_rl$D_IN;
  wire localFlitToHost_data_0_rl$EN;

  // register localFlitToHost_deqP_dummy2_0
  reg localFlitToHost_deqP_dummy2_0;
  wire localFlitToHost_deqP_dummy2_0$D_IN, localFlitToHost_deqP_dummy2_0$EN;

  // register localFlitToHost_deqP_dummy2_1
  reg localFlitToHost_deqP_dummy2_1;
  wire localFlitToHost_deqP_dummy2_1$D_IN, localFlitToHost_deqP_dummy2_1$EN;

  // register localFlitToHost_deqP_rl
  reg [1 : 0] localFlitToHost_deqP_rl;
  wire [1 : 0] localFlitToHost_deqP_rl$D_IN;
  wire localFlitToHost_deqP_rl$EN;

  // register localFlitToHost_enqP_dummy2_0
  reg localFlitToHost_enqP_dummy2_0;
  wire localFlitToHost_enqP_dummy2_0$D_IN, localFlitToHost_enqP_dummy2_0$EN;

  // register localFlitToHost_enqP_dummy2_1
  reg localFlitToHost_enqP_dummy2_1;
  wire localFlitToHost_enqP_dummy2_1$D_IN, localFlitToHost_enqP_dummy2_1$EN;

  // register localFlitToHost_enqP_rl
  reg [1 : 0] localFlitToHost_enqP_rl;
  wire [1 : 0] localFlitToHost_enqP_rl$D_IN;
  wire localFlitToHost_enqP_rl$EN;

  // register peID
  reg [6 : 0] peID;
  wire [6 : 0] peID$D_IN;
  wire peID$EN;

  // register scatterFlitFifo_data_0_dummy2_0
  reg scatterFlitFifo_data_0_dummy2_0;
  wire scatterFlitFifo_data_0_dummy2_0$D_IN,
       scatterFlitFifo_data_0_dummy2_0$EN;

  // register scatterFlitFifo_data_0_dummy2_1
  reg scatterFlitFifo_data_0_dummy2_1;
  wire scatterFlitFifo_data_0_dummy2_1$D_IN,
       scatterFlitFifo_data_0_dummy2_1$EN;

  // register scatterFlitFifo_data_0_rl
  reg [90 : 0] scatterFlitFifo_data_0_rl;
  wire [90 : 0] scatterFlitFifo_data_0_rl$D_IN;
  wire scatterFlitFifo_data_0_rl$EN;

  // register scatterFlitFifo_deqP_dummy2_0
  reg scatterFlitFifo_deqP_dummy2_0;
  wire scatterFlitFifo_deqP_dummy2_0$D_IN, scatterFlitFifo_deqP_dummy2_0$EN;

  // register scatterFlitFifo_deqP_dummy2_1
  reg scatterFlitFifo_deqP_dummy2_1;
  wire scatterFlitFifo_deqP_dummy2_1$D_IN, scatterFlitFifo_deqP_dummy2_1$EN;

  // register scatterFlitFifo_deqP_rl
  reg [1 : 0] scatterFlitFifo_deqP_rl;
  wire [1 : 0] scatterFlitFifo_deqP_rl$D_IN;
  wire scatterFlitFifo_deqP_rl$EN;

  // register scatterFlitFifo_enqP_dummy2_0
  reg scatterFlitFifo_enqP_dummy2_0;
  wire scatterFlitFifo_enqP_dummy2_0$D_IN, scatterFlitFifo_enqP_dummy2_0$EN;

  // register scatterFlitFifo_enqP_dummy2_1
  reg scatterFlitFifo_enqP_dummy2_1;
  wire scatterFlitFifo_enqP_dummy2_1$D_IN, scatterFlitFifo_enqP_dummy2_1$EN;

  // register scatterFlitFifo_enqP_rl
  reg [1 : 0] scatterFlitFifo_enqP_rl;
  wire [1 : 0] scatterFlitFifo_enqP_rl$D_IN;
  wire scatterFlitFifo_enqP_rl$EN;

  // rule scheduling signals
  wire WILL_FIRE_RL_deqLocalFifos,
       WILL_FIRE_RL_selectHostPortWinner,
       WILL_FIRE_RL_selectLocalPortWinner0,
       WILL_FIRE_RL_selectLocalPortWinner1;

  // inputs to muxes for submodule ports
  wire [1 : 0] MUX_localFlitOutFifos_2_deqP_lat_0$wset_1__VAL_1;
  wire MUX_localFlitOutFifos_2_deqP_dummy2_0$write_1__SEL_1;

  // remaining internal signals
  wire [90 : 0] IF_localFlitInFifos_0_data_0_lat_0_whas__08_TH_ETC___d111,
		IF_localFlitInFifos_1_data_0_lat_0_whas__29_TH_ETC___d132,
		IF_localFlitInFifos_2_data_0_lat_0_whas__50_TH_ETC___d153,
		IF_localFlitOutFifos_2_data_0_lat_0_whas__7_TH_ETC___d90,
		IF_scatterFlitFifo_data_0_lat_0_whas__4_THEN_s_ETC___d27;
  wire [6 : 0] x__h35581, x__h36745, x__h37020;
  wire [1 : 0] cnt1__h10142,
	       cnt1__h13247,
	       cnt1__h16352,
	       cnt1__h19783,
	       cnt1__h22888,
	       cnt1__h25993,
	       cnt1__h3429,
	       cnt1__h6728,
	       gatherFlitFifo_deqP_rl_PLUS_1__q2,
	       gatherFlitFifo_enqP_rl_PLUS_1__q1,
	       localFlitInFifos_0_deqP_rl_PLUS_1__q11,
	       localFlitInFifos_0_enqP_rl_PLUS_1__q10,
	       localFlitInFifos_1_deqP_rl_PLUS_1__q13,
	       localFlitInFifos_1_enqP_rl_PLUS_1__q12,
	       localFlitInFifos_2_deqP_rl_PLUS_1__q15,
	       localFlitInFifos_2_enqP_rl_PLUS_1__q14,
	       localFlitOutFifos_0_deqP_rl_PLUS_1__q7,
	       localFlitOutFifos_0_enqP_rl_PLUS_1__q5,
	       localFlitOutFifos_1_deqP_rl_PLUS_1__q8,
	       localFlitOutFifos_1_enqP_rl_PLUS_1__q6,
	       localFlitOutFifos_2_deqP_rl_PLUS_1__q16,
	       localFlitOutFifos_2_enqP_rl_PLUS_1__q9,
	       n__read__h33935,
	       n__read__h34595,
	       n__read__h35196,
	       n__read__h36357,
	       n__read__h44994,
	       n__read__h45996,
	       n__read__h48236,
	       n__read__h48692,
	       scatterFlitFifo_deqP_rl_PLUS_1__q4,
	       scatterFlitFifo_enqP_rl_PLUS_1__q3,
	       upd__h10096,
	       upd__h13201,
	       upd__h16306,
	       upd__h19737,
	       upd__h22842,
	       upd__h25947,
	       upd__h3383,
	       upd__h34063,
	       upd__h34723,
	       upd__h35324,
	       upd__h36485,
	       upd__h45047,
	       upd__h46049,
	       upd__h48289,
	       upd__h48745,
	       upd__h6682;
  wire IF_IF_localFlitInFifos_1_enqP_dummy2_1_65_THEN_ETC___d361,
       IF_IF_localFlitInFifos_2_enqP_dummy2_1_44_THEN_ETC___d386,
       IF_IF_localFlitInFifos_2_enqP_dummy2_1_44_THEN_ETC___d408,
       IF_deqBits_0_lat_1_whas__92_THEN_deqBits_0_lat_ETC___d198,
       IF_deqBits_1_lat_1_whas__02_THEN_deqBits_1_lat_ETC___d208,
       IF_deqBits_2_lat_1_whas__12_THEN_deqBits_2_lat_ETC___d218,
       IF_localFlitInFifos_0_data_0_dummy2_1_82_THEN__ETC___d287,
       IF_localFlitInFifos_1_data_0_dummy2_1_90_THEN__ETC___d295,
       IF_localFlitInFifos_2_data_0_dummy2_1_55_THEN__ETC___d261,
       IF_localFlitInFifos_2_data_0_dummy2_1_55_THEN__ETC___d275,
       NOT_IF_IF_localFlitInFifos_1_enqP_dummy2_1_65__ETC___d298;

  // action method gatherInPort_putFlit
  assign RDY_gatherInPort_putFlit =
	     ((gatherFlitFifo_enqP_rl < gatherFlitFifo_deqP_rl) ?
		2'd1 :
		gatherFlitFifo_enqP_rl - gatherFlitFifo_deqP_rl) ==
	     2'd0 &&
	     inited ;

  // actionvalue method gatherOutPort_getFlit
  assign gatherOutPort_getFlit =
	     EN_gatherInPort_putFlit ?
	       gatherInPort_putFlit_flit :
	       gatherFlitFifo_data_0_rl ;
  assign RDY_gatherOutPort_getFlit = cnt1__h3429 != 2'd0 && inited ;

  // action method scatterInPort_putFlit
  assign RDY_scatterInPort_putFlit =
	     ((scatterFlitFifo_enqP_rl < scatterFlitFifo_deqP_rl) ?
		2'd1 :
		scatterFlitFifo_enqP_rl - scatterFlitFifo_deqP_rl) ==
	     2'd0 &&
	     inited ;

  // actionvalue method scatterOutPort_getFlit
  assign scatterOutPort_getFlit =
	     (cnt1__h6728 == 2'd0) ?
	       IF_localFlitOutFifos_2_data_0_lat_0_whas__7_TH_ETC___d90 :
	       IF_scatterFlitFifo_data_0_lat_0_whas__4_THEN_s_ETC___d27 ;
  assign RDY_scatterOutPort_getFlit =
	     inited && (cnt1__h6728 != 2'd0 || cnt1__h16352 != 2'd0) ;

  // action method interPEInPort_0_putFlit
  assign RDY_interPEInPort_0_putFlit =
	     ((localFlitInFifos_0_enqP_rl < localFlitInFifos_0_deqP_rl) ?
		2'd1 :
		localFlitInFifos_0_enqP_rl - localFlitInFifos_0_deqP_rl) ==
	     2'd0 &&
	     inited ;

  // action method interPEInPort_1_putFlit
  assign RDY_interPEInPort_1_putFlit =
	     ((localFlitInFifos_1_enqP_rl < localFlitInFifos_1_deqP_rl) ?
		2'd1 :
		localFlitInFifos_1_enqP_rl - localFlitInFifos_1_deqP_rl) ==
	     2'd0 &&
	     inited ;

  // action method interPEInPort_2_putFlit
  assign RDY_interPEInPort_2_putFlit =
	     ((localFlitInFifos_2_enqP_rl < localFlitInFifos_2_deqP_rl) ?
		2'd1 :
		localFlitInFifos_2_enqP_rl - localFlitInFifos_2_deqP_rl) ==
	     2'd0 &&
	     inited ;

  // actionvalue method interPEOutPort_0_getFlit
  assign interPEOutPort_0_getFlit =
	     localFlitOutFifos_0_data_0_lat_0$whas ?
	       localFlitOutFifos_0_data_0_lat_0$wget :
	       localFlitOutFifos_0_data_0_rl ;
  assign RDY_interPEOutPort_0_getFlit = cnt1__h10142 != 2'd0 && inited ;

  // actionvalue method interPEOutPort_1_getFlit
  assign interPEOutPort_1_getFlit =
	     localFlitOutFifos_1_data_0_lat_0$whas ?
	       localFlitOutFifos_1_data_0_lat_0$wget :
	       localFlitOutFifos_1_data_0_rl ;
  assign RDY_interPEOutPort_1_getFlit = cnt1__h13247 != 2'd0 && inited ;

  // actionvalue method interPEOutPort_2_getFlit
  assign interPEOutPort_2_getFlit =
	     localFlitOutFifos_2_data_0_lat_0$whas ?
	       localFlitOutFifos_2_data_0_lat_0$wget :
	       localFlitOutFifos_2_data_0_rl ;
  assign RDY_interPEOutPort_2_getFlit = cnt1__h16352 != 2'd0 && inited ;

  // action method initialize
  assign RDY_initialize = !inited ;

  // rule RL_selectHostPortWinner
  assign WILL_FIRE_RL_selectHostPortWinner =
	     (cnt1__h19783 != 2'd0 &&
	      IF_localFlitInFifos_0_data_0_dummy2_1_82_THEN__ETC___d287) ?
	       ((localFlitOutFifos_2_enqP_rl < localFlitOutFifos_2_deqP_rl) ?
		  2'd1 :
		  localFlitOutFifos_2_enqP_rl -
		  localFlitOutFifos_2_deqP_rl) ==
	       2'd0 :
	       IF_IF_localFlitInFifos_1_enqP_dummy2_1_65_THEN_ETC___d361 ;

  // rule RL_selectLocalPortWinner0
  assign WILL_FIRE_RL_selectLocalPortWinner0 =
	     (cnt1__h19783 != 2'd0 &&
	      !IF_localFlitInFifos_0_data_0_dummy2_1_82_THEN__ETC___d287) ?
	       ((localFlitOutFifos_0_enqP_rl < localFlitOutFifos_0_deqP_rl) ?
		  2'd1 :
		  localFlitOutFifos_0_enqP_rl -
		  localFlitOutFifos_0_deqP_rl) ==
	       2'd0 :
	       IF_IF_localFlitInFifos_2_enqP_dummy2_1_44_THEN_ETC___d386 ;

  // rule RL_selectLocalPortWinner1
  assign WILL_FIRE_RL_selectLocalPortWinner1 =
	     (cnt1__h22888 != 2'd0 &&
	      !IF_localFlitInFifos_1_data_0_dummy2_1_90_THEN__ETC___d295) ?
	       ((localFlitOutFifos_1_enqP_rl < localFlitOutFifos_1_deqP_rl) ?
		  2'd1 :
		  localFlitOutFifos_1_enqP_rl -
		  localFlitOutFifos_1_deqP_rl) ==
	       2'd0 :
	       IF_IF_localFlitInFifos_2_enqP_dummy2_1_44_THEN_ETC___d408 ;

  // rule RL_deqLocalFifos
  assign WILL_FIRE_RL_deqLocalFifos =
	     (!(cnt1__h19783 != 2'd0) && !deqBits_0_rl ||
	      cnt1__h19783 != 2'd0) &&
	     (!NOT_IF_IF_localFlitInFifos_1_enqP_dummy2_1_65__ETC___d298 &&
	      !deqBits_1_rl ||
	      cnt1__h22888 != 2'd0) &&
	     (!deqBits_2_lat_1$whas && !deqBits_2_lat_0$whas &&
	      !deqBits_2_rl ||
	      cnt1__h25993 != 2'd0) ;

  // inputs to muxes for submodule ports
  assign MUX_localFlitOutFifos_2_deqP_dummy2_0$write_1__SEL_1 =
	     EN_scatterOutPort_getFlit && cnt1__h6728 == 2'd0 ;
  assign MUX_localFlitOutFifos_2_deqP_lat_0$wset_1__VAL_1 =
	     { 1'd0, localFlitOutFifos_2_deqP_rl_PLUS_1__q16[0] } ;

  // inlined wires
  assign gatherFlitFifo_enqP_lat_0$wget =
	     { 1'd0, gatherFlitFifo_enqP_rl_PLUS_1__q1[0] } ;
  assign gatherFlitFifo_deqP_lat_0$wget =
	     { 1'd0, gatherFlitFifo_deqP_rl_PLUS_1__q2[0] } ;
  assign scatterFlitFifo_enqP_lat_0$wget =
	     { 1'd0, scatterFlitFifo_enqP_rl_PLUS_1__q3[0] } ;
  assign scatterFlitFifo_deqP_lat_0$wget =
	     { 1'd0, scatterFlitFifo_deqP_rl_PLUS_1__q4[0] } ;
  assign localFlitOutFifos_0_data_0_lat_0$wget =
	     (cnt1__h19783 != 2'd0 &&
	      !IF_localFlitInFifos_0_data_0_dummy2_1_82_THEN__ETC___d287) ?
	       IF_localFlitInFifos_0_data_0_lat_0_whas__08_TH_ETC___d111 :
	       IF_localFlitInFifos_2_data_0_lat_0_whas__50_TH_ETC___d153 ;
  assign localFlitOutFifos_0_data_0_lat_0$whas =
	     WILL_FIRE_RL_selectLocalPortWinner0 &&
	     (cnt1__h19783 != 2'd0 &&
	      !IF_localFlitInFifos_0_data_0_dummy2_1_82_THEN__ETC___d287 ||
	      cnt1__h25993 != 2'd0 &&
	      IF_localFlitInFifos_2_data_0_dummy2_1_55_THEN__ETC___d261) ;
  assign localFlitOutFifos_1_data_0_lat_0$wget =
	     (cnt1__h22888 != 2'd0 &&
	      !IF_localFlitInFifos_1_data_0_dummy2_1_90_THEN__ETC___d295) ?
	       IF_localFlitInFifos_1_data_0_lat_0_whas__29_TH_ETC___d132 :
	       IF_localFlitInFifos_2_data_0_lat_0_whas__50_TH_ETC___d153 ;
  assign localFlitOutFifos_1_data_0_lat_0$whas =
	     WILL_FIRE_RL_selectLocalPortWinner1 &&
	     (cnt1__h22888 != 2'd0 &&
	      !IF_localFlitInFifos_1_data_0_dummy2_1_90_THEN__ETC___d295 ||
	      cnt1__h25993 != 2'd0 &&
	      !IF_localFlitInFifos_2_data_0_dummy2_1_55_THEN__ETC___d275) ;
  assign localFlitOutFifos_2_data_0_lat_0$wget =
	     (cnt1__h19783 != 2'd0 &&
	      IF_localFlitInFifos_0_data_0_dummy2_1_82_THEN__ETC___d287) ?
	       IF_localFlitInFifos_0_data_0_lat_0_whas__08_TH_ETC___d111 :
	       IF_localFlitInFifos_1_data_0_lat_0_whas__29_TH_ETC___d132 ;
  assign localFlitOutFifos_2_data_0_lat_0$whas =
	     WILL_FIRE_RL_selectHostPortWinner &&
	     (cnt1__h19783 != 2'd0 &&
	      IF_localFlitInFifos_0_data_0_dummy2_1_82_THEN__ETC___d287 ||
	      cnt1__h22888 != 2'd0 &&
	      IF_localFlitInFifos_1_data_0_dummy2_1_90_THEN__ETC___d295) ;
  assign localFlitOutFifos_2_deqP_lat_0$whas =
	     EN_scatterOutPort_getFlit && cnt1__h6728 == 2'd0 ||
	     EN_interPEOutPort_2_getFlit ;
  assign localFlitInFifos_0_deqP_lat_0$whas =
	     WILL_FIRE_RL_deqLocalFifos &&
	     IF_deqBits_0_lat_1_whas__92_THEN_deqBits_0_lat_ETC___d198 ;
  assign localFlitInFifos_1_deqP_lat_0$whas =
	     WILL_FIRE_RL_deqLocalFifos &&
	     IF_deqBits_1_lat_1_whas__02_THEN_deqBits_1_lat_ETC___d208 ;
  assign localFlitInFifos_2_deqP_lat_0$whas =
	     WILL_FIRE_RL_deqLocalFifos &&
	     IF_deqBits_2_lat_1_whas__12_THEN_deqBits_2_lat_ETC___d218 ;
  assign deqBits_2_lat_0$whas =
	     cnt1__h19783 == 2'd0 && cnt1__h25993 != 2'd0 &&
	     IF_localFlitInFifos_2_data_0_dummy2_1_55_THEN__ETC___d261 ;
  assign deqBits_2_lat_1$whas =
	     cnt1__h22888 == 2'd0 && cnt1__h25993 != 2'd0 &&
	     !IF_localFlitInFifos_2_data_0_dummy2_1_55_THEN__ETC___d275 ;

  // register controlSignal
  assign controlSignal$D_IN = 2'h0 ;
  assign controlSignal$EN = 1'b0 ;

  // register deqBits_0_dummy2_0
  assign deqBits_0_dummy2_0$D_IN = 1'd1 ;
  assign deqBits_0_dummy2_0$EN = cnt1__h19783 != 2'd0 ;

  // register deqBits_0_dummy2_1
  assign deqBits_0_dummy2_1$D_IN = 1'b0 ;
  assign deqBits_0_dummy2_1$EN = 1'b0 ;

  // register deqBits_0_dummy2_2
  assign deqBits_0_dummy2_2$D_IN = 1'd1 ;
  assign deqBits_0_dummy2_2$EN = localFlitInFifos_0_deqP_lat_0$whas ;

  // register deqBits_0_rl
  assign deqBits_0_rl$D_IN =
	     !localFlitInFifos_0_deqP_lat_0$whas &&
	     IF_deqBits_0_lat_1_whas__92_THEN_deqBits_0_lat_ETC___d198 ;
  assign deqBits_0_rl$EN = 1'd1 ;

  // register deqBits_1_dummy2_0
  assign deqBits_1_dummy2_0$D_IN = 1'd1 ;
  assign deqBits_1_dummy2_0$EN =
	     NOT_IF_IF_localFlitInFifos_1_enqP_dummy2_1_65__ETC___d298 ;

  // register deqBits_1_dummy2_1
  assign deqBits_1_dummy2_1$D_IN = 1'b0 ;
  assign deqBits_1_dummy2_1$EN = 1'b0 ;

  // register deqBits_1_dummy2_2
  assign deqBits_1_dummy2_2$D_IN = 1'd1 ;
  assign deqBits_1_dummy2_2$EN = localFlitInFifos_1_deqP_lat_0$whas ;

  // register deqBits_1_rl
  assign deqBits_1_rl$D_IN =
	     !localFlitInFifos_1_deqP_lat_0$whas &&
	     IF_deqBits_1_lat_1_whas__02_THEN_deqBits_1_lat_ETC___d208 ;
  assign deqBits_1_rl$EN = 1'd1 ;

  // register deqBits_2_dummy2_0
  assign deqBits_2_dummy2_0$D_IN = 1'd1 ;
  assign deqBits_2_dummy2_0$EN = deqBits_2_lat_0$whas ;

  // register deqBits_2_dummy2_1
  assign deqBits_2_dummy2_1$D_IN = 1'd1 ;
  assign deqBits_2_dummy2_1$EN = deqBits_2_lat_1$whas ;

  // register deqBits_2_dummy2_2
  assign deqBits_2_dummy2_2$D_IN = 1'd1 ;
  assign deqBits_2_dummy2_2$EN = localFlitInFifos_2_deqP_lat_0$whas ;

  // register deqBits_2_rl
  assign deqBits_2_rl$D_IN =
	     !localFlitInFifos_2_deqP_lat_0$whas &&
	     IF_deqBits_2_lat_1_whas__12_THEN_deqBits_2_lat_ETC___d218 ;
  assign deqBits_2_rl$EN = 1'd1 ;

  // register gatherFlitFifo_data_0_dummy2_0
  assign gatherFlitFifo_data_0_dummy2_0$D_IN = 1'd1 ;
  assign gatherFlitFifo_data_0_dummy2_0$EN = EN_gatherInPort_putFlit ;

  // register gatherFlitFifo_data_0_dummy2_1
  assign gatherFlitFifo_data_0_dummy2_1$D_IN = 1'b0 ;
  assign gatherFlitFifo_data_0_dummy2_1$EN = 1'b0 ;

  // register gatherFlitFifo_data_0_rl
  assign gatherFlitFifo_data_0_rl$D_IN =
	     EN_gatherInPort_putFlit ?
	       gatherInPort_putFlit_flit :
	       gatherFlitFifo_data_0_rl ;
  assign gatherFlitFifo_data_0_rl$EN = 1'd1 ;

  // register gatherFlitFifo_deqP_dummy2_0
  assign gatherFlitFifo_deqP_dummy2_0$D_IN = 1'd1 ;
  assign gatherFlitFifo_deqP_dummy2_0$EN = EN_gatherOutPort_getFlit ;

  // register gatherFlitFifo_deqP_dummy2_1
  assign gatherFlitFifo_deqP_dummy2_1$D_IN = 1'b0 ;
  assign gatherFlitFifo_deqP_dummy2_1$EN = 1'b0 ;

  // register gatherFlitFifo_deqP_rl
  assign gatherFlitFifo_deqP_rl$D_IN =
	     EN_gatherOutPort_getFlit ? upd__h3383 : gatherFlitFifo_deqP_rl ;
  assign gatherFlitFifo_deqP_rl$EN = 1'd1 ;

  // register gatherFlitFifo_enqP_dummy2_0
  assign gatherFlitFifo_enqP_dummy2_0$D_IN = 1'd1 ;
  assign gatherFlitFifo_enqP_dummy2_0$EN = EN_gatherInPort_putFlit ;

  // register gatherFlitFifo_enqP_dummy2_1
  assign gatherFlitFifo_enqP_dummy2_1$D_IN = 1'b0 ;
  assign gatherFlitFifo_enqP_dummy2_1$EN = 1'b0 ;

  // register gatherFlitFifo_enqP_rl
  assign gatherFlitFifo_enqP_rl$D_IN =
	     EN_gatherInPort_putFlit ? upd__h45047 : gatherFlitFifo_enqP_rl ;
  assign gatherFlitFifo_enqP_rl$EN = 1'd1 ;

  // register inited
  assign inited$D_IN = 1'd1 ;
  assign inited$EN = EN_initialize ;

  // register localFlitInFifos_0_data_0_dummy2_0
  assign localFlitInFifos_0_data_0_dummy2_0$D_IN = 1'd1 ;
  assign localFlitInFifos_0_data_0_dummy2_0$EN = EN_interPEInPort_0_putFlit ;

  // register localFlitInFifos_0_data_0_dummy2_1
  assign localFlitInFifos_0_data_0_dummy2_1$D_IN = 1'b0 ;
  assign localFlitInFifos_0_data_0_dummy2_1$EN = 1'b0 ;

  // register localFlitInFifos_0_data_0_rl
  assign localFlitInFifos_0_data_0_rl$D_IN =
	     IF_localFlitInFifos_0_data_0_lat_0_whas__08_TH_ETC___d111 ;
  assign localFlitInFifos_0_data_0_rl$EN = 1'd1 ;

  // register localFlitInFifos_0_deqP_dummy2_0
  assign localFlitInFifos_0_deqP_dummy2_0$D_IN = 1'd1 ;
  assign localFlitInFifos_0_deqP_dummy2_0$EN =
	     localFlitInFifos_0_deqP_lat_0$whas ;

  // register localFlitInFifos_0_deqP_dummy2_1
  assign localFlitInFifos_0_deqP_dummy2_1$D_IN = 1'b0 ;
  assign localFlitInFifos_0_deqP_dummy2_1$EN = 1'b0 ;

  // register localFlitInFifos_0_deqP_rl
  assign localFlitInFifos_0_deqP_rl$D_IN =
	     localFlitInFifos_0_deqP_lat_0$whas ?
	       upd__h19737 :
	       localFlitInFifos_0_deqP_rl ;
  assign localFlitInFifos_0_deqP_rl$EN = 1'd1 ;

  // register localFlitInFifos_0_enqP_dummy2_0
  assign localFlitInFifos_0_enqP_dummy2_0$D_IN = 1'd1 ;
  assign localFlitInFifos_0_enqP_dummy2_0$EN = EN_interPEInPort_0_putFlit ;

  // register localFlitInFifos_0_enqP_dummy2_1
  assign localFlitInFifos_0_enqP_dummy2_1$D_IN = 1'b0 ;
  assign localFlitInFifos_0_enqP_dummy2_1$EN = 1'b0 ;

  // register localFlitInFifos_0_enqP_rl
  assign localFlitInFifos_0_enqP_rl$D_IN = n__read__h34595 ;
  assign localFlitInFifos_0_enqP_rl$EN = 1'd1 ;

  // register localFlitInFifos_1_data_0_dummy2_0
  assign localFlitInFifos_1_data_0_dummy2_0$D_IN = 1'd1 ;
  assign localFlitInFifos_1_data_0_dummy2_0$EN = EN_interPEInPort_1_putFlit ;

  // register localFlitInFifos_1_data_0_dummy2_1
  assign localFlitInFifos_1_data_0_dummy2_1$D_IN = 1'b0 ;
  assign localFlitInFifos_1_data_0_dummy2_1$EN = 1'b0 ;

  // register localFlitInFifos_1_data_0_rl
  assign localFlitInFifos_1_data_0_rl$D_IN =
	     IF_localFlitInFifos_1_data_0_lat_0_whas__29_TH_ETC___d132 ;
  assign localFlitInFifos_1_data_0_rl$EN = 1'd1 ;

  // register localFlitInFifos_1_deqP_dummy2_0
  assign localFlitInFifos_1_deqP_dummy2_0$D_IN = 1'd1 ;
  assign localFlitInFifos_1_deqP_dummy2_0$EN =
	     localFlitInFifos_1_deqP_lat_0$whas ;

  // register localFlitInFifos_1_deqP_dummy2_1
  assign localFlitInFifos_1_deqP_dummy2_1$D_IN = 1'b0 ;
  assign localFlitInFifos_1_deqP_dummy2_1$EN = 1'b0 ;

  // register localFlitInFifos_1_deqP_rl
  assign localFlitInFifos_1_deqP_rl$D_IN =
	     localFlitInFifos_1_deqP_lat_0$whas ?
	       upd__h22842 :
	       localFlitInFifos_1_deqP_rl ;
  assign localFlitInFifos_1_deqP_rl$EN = 1'd1 ;

  // register localFlitInFifos_1_enqP_dummy2_0
  assign localFlitInFifos_1_enqP_dummy2_0$D_IN = 1'd1 ;
  assign localFlitInFifos_1_enqP_dummy2_0$EN = EN_interPEInPort_1_putFlit ;

  // register localFlitInFifos_1_enqP_dummy2_1
  assign localFlitInFifos_1_enqP_dummy2_1$D_IN = 1'b0 ;
  assign localFlitInFifos_1_enqP_dummy2_1$EN = 1'b0 ;

  // register localFlitInFifos_1_enqP_rl
  assign localFlitInFifos_1_enqP_rl$D_IN = n__read__h36357 ;
  assign localFlitInFifos_1_enqP_rl$EN = 1'd1 ;

  // register localFlitInFifos_2_data_0_dummy2_0
  assign localFlitInFifos_2_data_0_dummy2_0$D_IN = 1'd1 ;
  assign localFlitInFifos_2_data_0_dummy2_0$EN = EN_interPEInPort_2_putFlit ;

  // register localFlitInFifos_2_data_0_dummy2_1
  assign localFlitInFifos_2_data_0_dummy2_1$D_IN = 1'b0 ;
  assign localFlitInFifos_2_data_0_dummy2_1$EN = 1'b0 ;

  // register localFlitInFifos_2_data_0_rl
  assign localFlitInFifos_2_data_0_rl$D_IN =
	     IF_localFlitInFifos_2_data_0_lat_0_whas__50_TH_ETC___d153 ;
  assign localFlitInFifos_2_data_0_rl$EN = 1'd1 ;

  // register localFlitInFifos_2_deqP_dummy2_0
  assign localFlitInFifos_2_deqP_dummy2_0$D_IN = 1'd1 ;
  assign localFlitInFifos_2_deqP_dummy2_0$EN =
	     localFlitInFifos_2_deqP_lat_0$whas ;

  // register localFlitInFifos_2_deqP_dummy2_1
  assign localFlitInFifos_2_deqP_dummy2_1$D_IN = 1'b0 ;
  assign localFlitInFifos_2_deqP_dummy2_1$EN = 1'b0 ;

  // register localFlitInFifos_2_deqP_rl
  assign localFlitInFifos_2_deqP_rl$D_IN =
	     localFlitInFifos_2_deqP_lat_0$whas ?
	       upd__h25947 :
	       localFlitInFifos_2_deqP_rl ;
  assign localFlitInFifos_2_deqP_rl$EN = 1'd1 ;

  // register localFlitInFifos_2_enqP_dummy2_0
  assign localFlitInFifos_2_enqP_dummy2_0$D_IN = 1'd1 ;
  assign localFlitInFifos_2_enqP_dummy2_0$EN = EN_interPEInPort_2_putFlit ;

  // register localFlitInFifos_2_enqP_dummy2_1
  assign localFlitInFifos_2_enqP_dummy2_1$D_IN = 1'b0 ;
  assign localFlitInFifos_2_enqP_dummy2_1$EN = 1'b0 ;

  // register localFlitInFifos_2_enqP_rl
  assign localFlitInFifos_2_enqP_rl$D_IN = n__read__h35196 ;
  assign localFlitInFifos_2_enqP_rl$EN = 1'd1 ;

  // register localFlitOutFifos_0_data_0_dummy2_0
  assign localFlitOutFifos_0_data_0_dummy2_0$D_IN = 1'd1 ;
  assign localFlitOutFifos_0_data_0_dummy2_0$EN =
	     localFlitOutFifos_0_data_0_lat_0$whas ;

  // register localFlitOutFifos_0_data_0_dummy2_1
  assign localFlitOutFifos_0_data_0_dummy2_1$D_IN = 1'b0 ;
  assign localFlitOutFifos_0_data_0_dummy2_1$EN = 1'b0 ;

  // register localFlitOutFifos_0_data_0_rl
  assign localFlitOutFifos_0_data_0_rl$D_IN =
	     localFlitOutFifos_0_data_0_lat_0$whas ?
	       localFlitOutFifos_0_data_0_lat_0$wget :
	       localFlitOutFifos_0_data_0_rl ;
  assign localFlitOutFifos_0_data_0_rl$EN = 1'd1 ;

  // register localFlitOutFifos_0_deqP_dummy2_0
  assign localFlitOutFifos_0_deqP_dummy2_0$D_IN = 1'd1 ;
  assign localFlitOutFifos_0_deqP_dummy2_0$EN = EN_interPEOutPort_0_getFlit ;

  // register localFlitOutFifos_0_deqP_dummy2_1
  assign localFlitOutFifos_0_deqP_dummy2_1$D_IN = 1'b0 ;
  assign localFlitOutFifos_0_deqP_dummy2_1$EN = 1'b0 ;

  // register localFlitOutFifos_0_deqP_rl
  assign localFlitOutFifos_0_deqP_rl$D_IN =
	     EN_interPEOutPort_0_getFlit ?
	       upd__h10096 :
	       localFlitOutFifos_0_deqP_rl ;
  assign localFlitOutFifos_0_deqP_rl$EN = 1'd1 ;

  // register localFlitOutFifos_0_enqP_dummy2_0
  assign localFlitOutFifos_0_enqP_dummy2_0$D_IN = 1'd1 ;
  assign localFlitOutFifos_0_enqP_dummy2_0$EN =
	     localFlitOutFifos_0_data_0_lat_0$whas ;

  // register localFlitOutFifos_0_enqP_dummy2_1
  assign localFlitOutFifos_0_enqP_dummy2_1$D_IN = 1'b0 ;
  assign localFlitOutFifos_0_enqP_dummy2_1$EN = 1'b0 ;

  // register localFlitOutFifos_0_enqP_rl
  assign localFlitOutFifos_0_enqP_rl$D_IN = n__read__h48236 ;
  assign localFlitOutFifos_0_enqP_rl$EN = 1'd1 ;

  // register localFlitOutFifos_1_data_0_dummy2_0
  assign localFlitOutFifos_1_data_0_dummy2_0$D_IN = 1'd1 ;
  assign localFlitOutFifos_1_data_0_dummy2_0$EN =
	     localFlitOutFifos_1_data_0_lat_0$whas ;

  // register localFlitOutFifos_1_data_0_dummy2_1
  assign localFlitOutFifos_1_data_0_dummy2_1$D_IN = 1'b0 ;
  assign localFlitOutFifos_1_data_0_dummy2_1$EN = 1'b0 ;

  // register localFlitOutFifos_1_data_0_rl
  assign localFlitOutFifos_1_data_0_rl$D_IN =
	     localFlitOutFifos_1_data_0_lat_0$whas ?
	       localFlitOutFifos_1_data_0_lat_0$wget :
	       localFlitOutFifos_1_data_0_rl ;
  assign localFlitOutFifos_1_data_0_rl$EN = 1'd1 ;

  // register localFlitOutFifos_1_deqP_dummy2_0
  assign localFlitOutFifos_1_deqP_dummy2_0$D_IN = 1'd1 ;
  assign localFlitOutFifos_1_deqP_dummy2_0$EN = EN_interPEOutPort_1_getFlit ;

  // register localFlitOutFifos_1_deqP_dummy2_1
  assign localFlitOutFifos_1_deqP_dummy2_1$D_IN = 1'b0 ;
  assign localFlitOutFifos_1_deqP_dummy2_1$EN = 1'b0 ;

  // register localFlitOutFifos_1_deqP_rl
  assign localFlitOutFifos_1_deqP_rl$D_IN =
	     EN_interPEOutPort_1_getFlit ?
	       upd__h13201 :
	       localFlitOutFifos_1_deqP_rl ;
  assign localFlitOutFifos_1_deqP_rl$EN = 1'd1 ;

  // register localFlitOutFifos_1_enqP_dummy2_0
  assign localFlitOutFifos_1_enqP_dummy2_0$D_IN = 1'd1 ;
  assign localFlitOutFifos_1_enqP_dummy2_0$EN =
	     localFlitOutFifos_1_data_0_lat_0$whas ;

  // register localFlitOutFifos_1_enqP_dummy2_1
  assign localFlitOutFifos_1_enqP_dummy2_1$D_IN = 1'b0 ;
  assign localFlitOutFifos_1_enqP_dummy2_1$EN = 1'b0 ;

  // register localFlitOutFifos_1_enqP_rl
  assign localFlitOutFifos_1_enqP_rl$D_IN = n__read__h48692 ;
  assign localFlitOutFifos_1_enqP_rl$EN = 1'd1 ;

  // register localFlitOutFifos_2_data_0_dummy2_0
  assign localFlitOutFifos_2_data_0_dummy2_0$D_IN = 1'd1 ;
  assign localFlitOutFifos_2_data_0_dummy2_0$EN =
	     localFlitOutFifos_2_data_0_lat_0$whas ;

  // register localFlitOutFifos_2_data_0_dummy2_1
  assign localFlitOutFifos_2_data_0_dummy2_1$D_IN = 1'b0 ;
  assign localFlitOutFifos_2_data_0_dummy2_1$EN = 1'b0 ;

  // register localFlitOutFifos_2_data_0_rl
  assign localFlitOutFifos_2_data_0_rl$D_IN =
	     IF_localFlitOutFifos_2_data_0_lat_0_whas__7_TH_ETC___d90 ;
  assign localFlitOutFifos_2_data_0_rl$EN = 1'd1 ;

  // register localFlitOutFifos_2_deqP_dummy2_0
  assign localFlitOutFifos_2_deqP_dummy2_0$D_IN = 1'd1 ;
  assign localFlitOutFifos_2_deqP_dummy2_0$EN =
	     localFlitOutFifos_2_deqP_lat_0$whas ;

  // register localFlitOutFifos_2_deqP_dummy2_1
  assign localFlitOutFifos_2_deqP_dummy2_1$D_IN = 1'b0 ;
  assign localFlitOutFifos_2_deqP_dummy2_1$EN = 1'b0 ;

  // register localFlitOutFifos_2_deqP_rl
  assign localFlitOutFifos_2_deqP_rl$D_IN =
	     localFlitOutFifos_2_deqP_lat_0$whas ?
	       upd__h16306 :
	       localFlitOutFifos_2_deqP_rl ;
  assign localFlitOutFifos_2_deqP_rl$EN = 1'd1 ;

  // register localFlitOutFifos_2_enqP_dummy2_0
  assign localFlitOutFifos_2_enqP_dummy2_0$D_IN = 1'd1 ;
  assign localFlitOutFifos_2_enqP_dummy2_0$EN =
	     localFlitOutFifos_2_data_0_lat_0$whas ;

  // register localFlitOutFifos_2_enqP_dummy2_1
  assign localFlitOutFifos_2_enqP_dummy2_1$D_IN = 1'b0 ;
  assign localFlitOutFifos_2_enqP_dummy2_1$EN = 1'b0 ;

  // register localFlitOutFifos_2_enqP_rl
  assign localFlitOutFifos_2_enqP_rl$D_IN = n__read__h45996 ;
  assign localFlitOutFifos_2_enqP_rl$EN = 1'd1 ;

  // register localFlitToHost_data_0_dummy2_0
  assign localFlitToHost_data_0_dummy2_0$D_IN = 1'b0 ;
  assign localFlitToHost_data_0_dummy2_0$EN = 1'b0 ;

  // register localFlitToHost_data_0_dummy2_1
  assign localFlitToHost_data_0_dummy2_1$D_IN = 1'b0 ;
  assign localFlitToHost_data_0_dummy2_1$EN = 1'b0 ;

  // register localFlitToHost_data_0_rl
  assign localFlitToHost_data_0_rl$D_IN = localFlitToHost_data_0_rl ;
  assign localFlitToHost_data_0_rl$EN = 1'd1 ;

  // register localFlitToHost_deqP_dummy2_0
  assign localFlitToHost_deqP_dummy2_0$D_IN = 1'b0 ;
  assign localFlitToHost_deqP_dummy2_0$EN = 1'b0 ;

  // register localFlitToHost_deqP_dummy2_1
  assign localFlitToHost_deqP_dummy2_1$D_IN = 1'b0 ;
  assign localFlitToHost_deqP_dummy2_1$EN = 1'b0 ;

  // register localFlitToHost_deqP_rl
  assign localFlitToHost_deqP_rl$D_IN = localFlitToHost_deqP_rl ;
  assign localFlitToHost_deqP_rl$EN = 1'd1 ;

  // register localFlitToHost_enqP_dummy2_0
  assign localFlitToHost_enqP_dummy2_0$D_IN = 1'b0 ;
  assign localFlitToHost_enqP_dummy2_0$EN = 1'b0 ;

  // register localFlitToHost_enqP_dummy2_1
  assign localFlitToHost_enqP_dummy2_1$D_IN = 1'b0 ;
  assign localFlitToHost_enqP_dummy2_1$EN = 1'b0 ;

  // register localFlitToHost_enqP_rl
  assign localFlitToHost_enqP_rl$D_IN = localFlitToHost_enqP_rl ;
  assign localFlitToHost_enqP_rl$EN = 1'd1 ;

  // register peID
  assign peID$D_IN = initialize_initPEID ;
  assign peID$EN = EN_initialize ;

  // register scatterFlitFifo_data_0_dummy2_0
  assign scatterFlitFifo_data_0_dummy2_0$D_IN = 1'd1 ;
  assign scatterFlitFifo_data_0_dummy2_0$EN = EN_scatterInPort_putFlit ;

  // register scatterFlitFifo_data_0_dummy2_1
  assign scatterFlitFifo_data_0_dummy2_1$D_IN = 1'b0 ;
  assign scatterFlitFifo_data_0_dummy2_1$EN = 1'b0 ;

  // register scatterFlitFifo_data_0_rl
  assign scatterFlitFifo_data_0_rl$D_IN =
	     IF_scatterFlitFifo_data_0_lat_0_whas__4_THEN_s_ETC___d27 ;
  assign scatterFlitFifo_data_0_rl$EN = 1'd1 ;

  // register scatterFlitFifo_deqP_dummy2_0
  assign scatterFlitFifo_deqP_dummy2_0$D_IN = 1'd1 ;
  assign scatterFlitFifo_deqP_dummy2_0$EN = cnt1__h6728 != 2'd0 ;

  // register scatterFlitFifo_deqP_dummy2_1
  assign scatterFlitFifo_deqP_dummy2_1$D_IN = 1'b0 ;
  assign scatterFlitFifo_deqP_dummy2_1$EN = 1'b0 ;

  // register scatterFlitFifo_deqP_rl
  assign scatterFlitFifo_deqP_rl$D_IN =
	     (cnt1__h6728 != 2'd0) ? upd__h6682 : scatterFlitFifo_deqP_rl ;
  assign scatterFlitFifo_deqP_rl$EN = 1'd1 ;

  // register scatterFlitFifo_enqP_dummy2_0
  assign scatterFlitFifo_enqP_dummy2_0$D_IN = 1'd1 ;
  assign scatterFlitFifo_enqP_dummy2_0$EN = EN_scatterInPort_putFlit ;

  // register scatterFlitFifo_enqP_dummy2_1
  assign scatterFlitFifo_enqP_dummy2_1$D_IN = 1'b0 ;
  assign scatterFlitFifo_enqP_dummy2_1$EN = 1'b0 ;

  // register scatterFlitFifo_enqP_rl
  assign scatterFlitFifo_enqP_rl$D_IN =
	     EN_scatterInPort_putFlit ?
	       upd__h34063 :
	       scatterFlitFifo_enqP_rl ;
  assign scatterFlitFifo_enqP_rl$EN = 1'd1 ;

  // remaining internal signals
  assign IF_IF_localFlitInFifos_1_enqP_dummy2_1_65_THEN_ETC___d361 =
	     cnt1__h22888 == 2'd0 ||
	     !IF_localFlitInFifos_1_data_0_dummy2_1_90_THEN__ETC___d295 ||
	     ((localFlitOutFifos_2_enqP_rl < localFlitOutFifos_2_deqP_rl) ?
		2'd1 :
		localFlitOutFifos_2_enqP_rl - localFlitOutFifos_2_deqP_rl) ==
	     2'd0 ;
  assign IF_IF_localFlitInFifos_2_enqP_dummy2_1_44_THEN_ETC___d386 =
	     cnt1__h25993 == 2'd0 ||
	     !IF_localFlitInFifos_2_data_0_dummy2_1_55_THEN__ETC___d261 ||
	     ((localFlitOutFifos_0_enqP_rl < localFlitOutFifos_0_deqP_rl) ?
		2'd1 :
		localFlitOutFifos_0_enqP_rl - localFlitOutFifos_0_deqP_rl) ==
	     2'd0 ;
  assign IF_IF_localFlitInFifos_2_enqP_dummy2_1_44_THEN_ETC___d408 =
	     cnt1__h25993 == 2'd0 ||
	     IF_localFlitInFifos_2_data_0_dummy2_1_55_THEN__ETC___d275 ||
	     ((localFlitOutFifos_1_enqP_rl < localFlitOutFifos_1_deqP_rl) ?
		2'd1 :
		localFlitOutFifos_1_enqP_rl - localFlitOutFifos_1_deqP_rl) ==
	     2'd0 ;
  assign IF_deqBits_0_lat_1_whas__92_THEN_deqBits_0_lat_ETC___d198 =
	     cnt1__h19783 != 2'd0 || deqBits_0_rl ;
  assign IF_deqBits_1_lat_1_whas__02_THEN_deqBits_1_lat_ETC___d208 =
	     NOT_IF_IF_localFlitInFifos_1_enqP_dummy2_1_65__ETC___d298 ||
	     deqBits_1_rl ;
  assign IF_deqBits_2_lat_1_whas__12_THEN_deqBits_2_lat_ETC___d218 =
	     deqBits_2_lat_1$whas || deqBits_2_lat_0$whas || deqBits_2_rl ;
  assign IF_localFlitInFifos_0_data_0_dummy2_1_82_THEN__ETC___d287 =
	     x__h36745 == peID ;
  assign IF_localFlitInFifos_0_data_0_lat_0_whas__08_TH_ETC___d111 =
	     EN_interPEInPort_0_putFlit ?
	       interPEInPort_0_putFlit_flit :
	       localFlitInFifos_0_data_0_rl ;
  assign IF_localFlitInFifos_1_data_0_dummy2_1_90_THEN__ETC___d295 =
	     x__h37020 == peID ;
  assign IF_localFlitInFifos_1_data_0_lat_0_whas__29_TH_ETC___d132 =
	     EN_interPEInPort_1_putFlit ?
	       interPEInPort_1_putFlit_flit :
	       localFlitInFifos_1_data_0_rl ;
  assign IF_localFlitInFifos_2_data_0_dummy2_1_55_THEN__ETC___d261 =
	     x__h35581 < peID ;
  assign IF_localFlitInFifos_2_data_0_dummy2_1_55_THEN__ETC___d275 =
	     x__h35581 <= peID ;
  assign IF_localFlitInFifos_2_data_0_lat_0_whas__50_TH_ETC___d153 =
	     EN_interPEInPort_2_putFlit ?
	       interPEInPort_2_putFlit_flit :
	       localFlitInFifos_2_data_0_rl ;
  assign IF_localFlitOutFifos_2_data_0_lat_0_whas__7_TH_ETC___d90 =
	     localFlitOutFifos_2_data_0_lat_0$whas ?
	       localFlitOutFifos_2_data_0_lat_0$wget :
	       localFlitOutFifos_2_data_0_rl ;
  assign IF_scatterFlitFifo_data_0_lat_0_whas__4_THEN_s_ETC___d27 =
	     EN_scatterInPort_putFlit ?
	       scatterInPort_putFlit_flit :
	       scatterFlitFifo_data_0_rl ;
  assign NOT_IF_IF_localFlitInFifos_1_enqP_dummy2_1_65__ETC___d298 =
	     cnt1__h22888 != 2'd0 &&
	     (cnt1__h19783 == 2'd0 ||
	      !IF_localFlitInFifos_0_data_0_dummy2_1_82_THEN__ETC___d287 ||
	      !IF_localFlitInFifos_1_data_0_dummy2_1_90_THEN__ETC___d295) ;
  assign cnt1__h10142 =
	     (n__read__h48236 < localFlitOutFifos_0_deqP_rl) ?
	       2'd1 :
	       n__read__h48236 - localFlitOutFifos_0_deqP_rl ;
  assign cnt1__h13247 =
	     (n__read__h48692 < localFlitOutFifos_1_deqP_rl) ?
	       2'd1 :
	       n__read__h48692 - localFlitOutFifos_1_deqP_rl ;
  assign cnt1__h16352 =
	     (n__read__h45996 < localFlitOutFifos_2_deqP_rl) ?
	       2'd1 :
	       n__read__h45996 - localFlitOutFifos_2_deqP_rl ;
  assign cnt1__h19783 =
	     (n__read__h34595 < localFlitInFifos_0_deqP_rl) ?
	       2'd1 :
	       n__read__h34595 - localFlitInFifos_0_deqP_rl ;
  assign cnt1__h22888 =
	     (n__read__h36357 < localFlitInFifos_1_deqP_rl) ?
	       2'd1 :
	       n__read__h36357 - localFlitInFifos_1_deqP_rl ;
  assign cnt1__h25993 =
	     (n__read__h35196 < localFlitInFifos_2_deqP_rl) ?
	       2'd1 :
	       n__read__h35196 - localFlitInFifos_2_deqP_rl ;
  assign cnt1__h3429 =
	     (n__read__h44994 < gatherFlitFifo_deqP_rl) ?
	       2'd1 :
	       n__read__h44994 - gatherFlitFifo_deqP_rl ;
  assign cnt1__h6728 =
	     (n__read__h33935 < scatterFlitFifo_deqP_rl) ?
	       2'd1 :
	       n__read__h33935 - scatterFlitFifo_deqP_rl ;
  assign gatherFlitFifo_deqP_rl_PLUS_1__q2 = gatherFlitFifo_deqP_rl + 2'd1 ;
  assign gatherFlitFifo_enqP_rl_PLUS_1__q1 = gatherFlitFifo_enqP_rl + 2'd1 ;
  assign localFlitInFifos_0_deqP_rl_PLUS_1__q11 =
	     localFlitInFifos_0_deqP_rl + 2'd1 ;
  assign localFlitInFifos_0_enqP_rl_PLUS_1__q10 =
	     localFlitInFifos_0_enqP_rl + 2'd1 ;
  assign localFlitInFifos_1_deqP_rl_PLUS_1__q13 =
	     localFlitInFifos_1_deqP_rl + 2'd1 ;
  assign localFlitInFifos_1_enqP_rl_PLUS_1__q12 =
	     localFlitInFifos_1_enqP_rl + 2'd1 ;
  assign localFlitInFifos_2_deqP_rl_PLUS_1__q15 =
	     localFlitInFifos_2_deqP_rl + 2'd1 ;
  assign localFlitInFifos_2_enqP_rl_PLUS_1__q14 =
	     localFlitInFifos_2_enqP_rl + 2'd1 ;
  assign localFlitOutFifos_0_deqP_rl_PLUS_1__q7 =
	     localFlitOutFifos_0_deqP_rl + 2'd1 ;
  assign localFlitOutFifos_0_enqP_rl_PLUS_1__q5 =
	     localFlitOutFifos_0_enqP_rl + 2'd1 ;
  assign localFlitOutFifos_1_deqP_rl_PLUS_1__q8 =
	     localFlitOutFifos_1_deqP_rl + 2'd1 ;
  assign localFlitOutFifos_1_enqP_rl_PLUS_1__q6 =
	     localFlitOutFifos_1_enqP_rl + 2'd1 ;
  assign localFlitOutFifos_2_deqP_rl_PLUS_1__q16 =
	     localFlitOutFifos_2_deqP_rl + 2'd1 ;
  assign localFlitOutFifos_2_enqP_rl_PLUS_1__q9 =
	     localFlitOutFifos_2_enqP_rl + 2'd1 ;
  assign n__read__h33935 =
	     EN_scatterInPort_putFlit ?
	       upd__h34063 :
	       scatterFlitFifo_enqP_rl ;
  assign n__read__h34595 =
	     EN_interPEInPort_0_putFlit ?
	       upd__h34723 :
	       localFlitInFifos_0_enqP_rl ;
  assign n__read__h35196 =
	     EN_interPEInPort_2_putFlit ?
	       upd__h35324 :
	       localFlitInFifos_2_enqP_rl ;
  assign n__read__h36357 =
	     EN_interPEInPort_1_putFlit ?
	       upd__h36485 :
	       localFlitInFifos_1_enqP_rl ;
  assign n__read__h44994 =
	     EN_gatherInPort_putFlit ? upd__h45047 : gatherFlitFifo_enqP_rl ;
  assign n__read__h45996 =
	     localFlitOutFifos_2_data_0_lat_0$whas ?
	       upd__h46049 :
	       localFlitOutFifos_2_enqP_rl ;
  assign n__read__h48236 =
	     localFlitOutFifos_0_data_0_lat_0$whas ?
	       upd__h48289 :
	       localFlitOutFifos_0_enqP_rl ;
  assign n__read__h48692 =
	     localFlitOutFifos_1_data_0_lat_0$whas ?
	       upd__h48745 :
	       localFlitOutFifos_1_enqP_rl ;
  assign scatterFlitFifo_deqP_rl_PLUS_1__q4 = scatterFlitFifo_deqP_rl + 2'd1 ;
  assign scatterFlitFifo_enqP_rl_PLUS_1__q3 = scatterFlitFifo_enqP_rl + 2'd1 ;
  assign upd__h10096 = { 1'd0, localFlitOutFifos_0_deqP_rl_PLUS_1__q7[0] } ;
  assign upd__h13201 = { 1'd0, localFlitOutFifos_1_deqP_rl_PLUS_1__q8[0] } ;
  assign upd__h16306 =
	     MUX_localFlitOutFifos_2_deqP_dummy2_0$write_1__SEL_1 ?
	       MUX_localFlitOutFifos_2_deqP_lat_0$wset_1__VAL_1 :
	       MUX_localFlitOutFifos_2_deqP_lat_0$wset_1__VAL_1 ;
  assign upd__h19737 = { 1'd0, localFlitInFifos_0_deqP_rl_PLUS_1__q11[0] } ;
  assign upd__h22842 = { 1'd0, localFlitInFifos_1_deqP_rl_PLUS_1__q13[0] } ;
  assign upd__h25947 = { 1'd0, localFlitInFifos_2_deqP_rl_PLUS_1__q15[0] } ;
  assign upd__h3383 = gatherFlitFifo_deqP_lat_0$wget ;
  assign upd__h34063 = scatterFlitFifo_enqP_lat_0$wget ;
  assign upd__h34723 = { 1'd0, localFlitInFifos_0_enqP_rl_PLUS_1__q10[0] } ;
  assign upd__h35324 = { 1'd0, localFlitInFifos_2_enqP_rl_PLUS_1__q14[0] } ;
  assign upd__h36485 = { 1'd0, localFlitInFifos_1_enqP_rl_PLUS_1__q12[0] } ;
  assign upd__h45047 = gatherFlitFifo_enqP_lat_0$wget ;
  assign upd__h46049 = { 1'd0, localFlitOutFifos_2_enqP_rl_PLUS_1__q9[0] } ;
  assign upd__h48289 = { 1'd0, localFlitOutFifos_0_enqP_rl_PLUS_1__q5[0] } ;
  assign upd__h48745 = { 1'd0, localFlitOutFifos_1_enqP_rl_PLUS_1__q6[0] } ;
  assign upd__h6682 = scatterFlitFifo_deqP_lat_0$wget ;
  assign x__h35581 =
	     EN_interPEInPort_2_putFlit ?
	       interPEInPort_2_putFlit_flit[22:16] :
	       localFlitInFifos_2_data_0_rl[22:16] ;
  assign x__h36745 =
	     EN_interPEInPort_0_putFlit ?
	       interPEInPort_0_putFlit_flit[22:16] :
	       localFlitInFifos_0_data_0_rl[22:16] ;
  assign x__h37020 =
	     EN_interPEInPort_1_putFlit ?
	       interPEInPort_1_putFlit_flit[22:16] :
	       localFlitInFifos_1_data_0_rl[22:16] ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        controlSignal <= `BSV_ASSIGNMENT_DELAY 2'd0;
	deqBits_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	deqBits_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	deqBits_0_dummy2_2 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	deqBits_0_rl <= `BSV_ASSIGNMENT_DELAY 1'd0;
	deqBits_1_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	deqBits_1_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	deqBits_1_dummy2_2 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	deqBits_1_rl <= `BSV_ASSIGNMENT_DELAY 1'd0;
	deqBits_2_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	deqBits_2_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	deqBits_2_dummy2_2 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	deqBits_2_rl <= `BSV_ASSIGNMENT_DELAY 1'd0;
	gatherFlitFifo_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherFlitFifo_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherFlitFifo_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	    91'h2AAAAAAAAAAAAAAAAAAAAAA;
	gatherFlitFifo_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherFlitFifo_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherFlitFifo_deqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	gatherFlitFifo_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherFlitFifo_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherFlitFifo_enqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	inited <= `BSV_ASSIGNMENT_DELAY 1'd0;
	localFlitInFifos_0_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_0_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_0_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	    91'h2AAAAAAAAAAAAAAAAAAAAAA;
	localFlitInFifos_0_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_0_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_0_deqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	localFlitInFifos_0_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_0_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_0_enqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	localFlitInFifos_1_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_1_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_1_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	    91'h2AAAAAAAAAAAAAAAAAAAAAA;
	localFlitInFifos_1_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_1_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_1_deqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	localFlitInFifos_1_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_1_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_1_enqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	localFlitInFifos_2_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_2_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_2_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	    91'h2AAAAAAAAAAAAAAAAAAAAAA;
	localFlitInFifos_2_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_2_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_2_deqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	localFlitInFifos_2_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_2_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitInFifos_2_enqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	localFlitOutFifos_0_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_0_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_0_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	    91'h2AAAAAAAAAAAAAAAAAAAAAA;
	localFlitOutFifos_0_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_0_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_0_deqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	localFlitOutFifos_0_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_0_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_0_enqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	localFlitOutFifos_1_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_1_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_1_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	    91'h2AAAAAAAAAAAAAAAAAAAAAA;
	localFlitOutFifos_1_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_1_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_1_deqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	localFlitOutFifos_1_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_1_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_1_enqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	localFlitOutFifos_2_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_2_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_2_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	    91'h2AAAAAAAAAAAAAAAAAAAAAA;
	localFlitOutFifos_2_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_2_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_2_deqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	localFlitOutFifos_2_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_2_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitOutFifos_2_enqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	localFlitToHost_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitToHost_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitToHost_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	    91'h2AAAAAAAAAAAAAAAAAAAAAA;
	localFlitToHost_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitToHost_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitToHost_deqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	localFlitToHost_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitToHost_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	localFlitToHost_enqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	scatterFlitFifo_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFlitFifo_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFlitFifo_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	    91'h2AAAAAAAAAAAAAAAAAAAAAA;
	scatterFlitFifo_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFlitFifo_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFlitFifo_deqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	scatterFlitFifo_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFlitFifo_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFlitFifo_enqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
      end
    else
      begin
        if (controlSignal$EN)
	  controlSignal <= `BSV_ASSIGNMENT_DELAY controlSignal$D_IN;
	if (deqBits_0_dummy2_0$EN)
	  deqBits_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY deqBits_0_dummy2_0$D_IN;
	if (deqBits_0_dummy2_1$EN)
	  deqBits_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY deqBits_0_dummy2_1$D_IN;
	if (deqBits_0_dummy2_2$EN)
	  deqBits_0_dummy2_2 <= `BSV_ASSIGNMENT_DELAY deqBits_0_dummy2_2$D_IN;
	if (deqBits_0_rl$EN)
	  deqBits_0_rl <= `BSV_ASSIGNMENT_DELAY deqBits_0_rl$D_IN;
	if (deqBits_1_dummy2_0$EN)
	  deqBits_1_dummy2_0 <= `BSV_ASSIGNMENT_DELAY deqBits_1_dummy2_0$D_IN;
	if (deqBits_1_dummy2_1$EN)
	  deqBits_1_dummy2_1 <= `BSV_ASSIGNMENT_DELAY deqBits_1_dummy2_1$D_IN;
	if (deqBits_1_dummy2_2$EN)
	  deqBits_1_dummy2_2 <= `BSV_ASSIGNMENT_DELAY deqBits_1_dummy2_2$D_IN;
	if (deqBits_1_rl$EN)
	  deqBits_1_rl <= `BSV_ASSIGNMENT_DELAY deqBits_1_rl$D_IN;
	if (deqBits_2_dummy2_0$EN)
	  deqBits_2_dummy2_0 <= `BSV_ASSIGNMENT_DELAY deqBits_2_dummy2_0$D_IN;
	if (deqBits_2_dummy2_1$EN)
	  deqBits_2_dummy2_1 <= `BSV_ASSIGNMENT_DELAY deqBits_2_dummy2_1$D_IN;
	if (deqBits_2_dummy2_2$EN)
	  deqBits_2_dummy2_2 <= `BSV_ASSIGNMENT_DELAY deqBits_2_dummy2_2$D_IN;
	if (deqBits_2_rl$EN)
	  deqBits_2_rl <= `BSV_ASSIGNMENT_DELAY deqBits_2_rl$D_IN;
	if (gatherFlitFifo_data_0_dummy2_0$EN)
	  gatherFlitFifo_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_data_0_dummy2_0$D_IN;
	if (gatherFlitFifo_data_0_dummy2_1$EN)
	  gatherFlitFifo_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_data_0_dummy2_1$D_IN;
	if (gatherFlitFifo_data_0_rl$EN)
	  gatherFlitFifo_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_data_0_rl$D_IN;
	if (gatherFlitFifo_deqP_dummy2_0$EN)
	  gatherFlitFifo_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_deqP_dummy2_0$D_IN;
	if (gatherFlitFifo_deqP_dummy2_1$EN)
	  gatherFlitFifo_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_deqP_dummy2_1$D_IN;
	if (gatherFlitFifo_deqP_rl$EN)
	  gatherFlitFifo_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_deqP_rl$D_IN;
	if (gatherFlitFifo_enqP_dummy2_0$EN)
	  gatherFlitFifo_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_enqP_dummy2_0$D_IN;
	if (gatherFlitFifo_enqP_dummy2_1$EN)
	  gatherFlitFifo_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_enqP_dummy2_1$D_IN;
	if (gatherFlitFifo_enqP_rl$EN)
	  gatherFlitFifo_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_enqP_rl$D_IN;
	if (inited$EN) inited <= `BSV_ASSIGNMENT_DELAY inited$D_IN;
	if (localFlitInFifos_0_data_0_dummy2_0$EN)
	  localFlitInFifos_0_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_0_data_0_dummy2_0$D_IN;
	if (localFlitInFifos_0_data_0_dummy2_1$EN)
	  localFlitInFifos_0_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_0_data_0_dummy2_1$D_IN;
	if (localFlitInFifos_0_data_0_rl$EN)
	  localFlitInFifos_0_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_0_data_0_rl$D_IN;
	if (localFlitInFifos_0_deqP_dummy2_0$EN)
	  localFlitInFifos_0_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_0_deqP_dummy2_0$D_IN;
	if (localFlitInFifos_0_deqP_dummy2_1$EN)
	  localFlitInFifos_0_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_0_deqP_dummy2_1$D_IN;
	if (localFlitInFifos_0_deqP_rl$EN)
	  localFlitInFifos_0_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_0_deqP_rl$D_IN;
	if (localFlitInFifos_0_enqP_dummy2_0$EN)
	  localFlitInFifos_0_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_0_enqP_dummy2_0$D_IN;
	if (localFlitInFifos_0_enqP_dummy2_1$EN)
	  localFlitInFifos_0_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_0_enqP_dummy2_1$D_IN;
	if (localFlitInFifos_0_enqP_rl$EN)
	  localFlitInFifos_0_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_0_enqP_rl$D_IN;
	if (localFlitInFifos_1_data_0_dummy2_0$EN)
	  localFlitInFifos_1_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_1_data_0_dummy2_0$D_IN;
	if (localFlitInFifos_1_data_0_dummy2_1$EN)
	  localFlitInFifos_1_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_1_data_0_dummy2_1$D_IN;
	if (localFlitInFifos_1_data_0_rl$EN)
	  localFlitInFifos_1_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_1_data_0_rl$D_IN;
	if (localFlitInFifos_1_deqP_dummy2_0$EN)
	  localFlitInFifos_1_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_1_deqP_dummy2_0$D_IN;
	if (localFlitInFifos_1_deqP_dummy2_1$EN)
	  localFlitInFifos_1_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_1_deqP_dummy2_1$D_IN;
	if (localFlitInFifos_1_deqP_rl$EN)
	  localFlitInFifos_1_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_1_deqP_rl$D_IN;
	if (localFlitInFifos_1_enqP_dummy2_0$EN)
	  localFlitInFifos_1_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_1_enqP_dummy2_0$D_IN;
	if (localFlitInFifos_1_enqP_dummy2_1$EN)
	  localFlitInFifos_1_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_1_enqP_dummy2_1$D_IN;
	if (localFlitInFifos_1_enqP_rl$EN)
	  localFlitInFifos_1_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_1_enqP_rl$D_IN;
	if (localFlitInFifos_2_data_0_dummy2_0$EN)
	  localFlitInFifos_2_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_2_data_0_dummy2_0$D_IN;
	if (localFlitInFifos_2_data_0_dummy2_1$EN)
	  localFlitInFifos_2_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_2_data_0_dummy2_1$D_IN;
	if (localFlitInFifos_2_data_0_rl$EN)
	  localFlitInFifos_2_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_2_data_0_rl$D_IN;
	if (localFlitInFifos_2_deqP_dummy2_0$EN)
	  localFlitInFifos_2_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_2_deqP_dummy2_0$D_IN;
	if (localFlitInFifos_2_deqP_dummy2_1$EN)
	  localFlitInFifos_2_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_2_deqP_dummy2_1$D_IN;
	if (localFlitInFifos_2_deqP_rl$EN)
	  localFlitInFifos_2_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_2_deqP_rl$D_IN;
	if (localFlitInFifos_2_enqP_dummy2_0$EN)
	  localFlitInFifos_2_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_2_enqP_dummy2_0$D_IN;
	if (localFlitInFifos_2_enqP_dummy2_1$EN)
	  localFlitInFifos_2_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_2_enqP_dummy2_1$D_IN;
	if (localFlitInFifos_2_enqP_rl$EN)
	  localFlitInFifos_2_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitInFifos_2_enqP_rl$D_IN;
	if (localFlitOutFifos_0_data_0_dummy2_0$EN)
	  localFlitOutFifos_0_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_0_data_0_dummy2_0$D_IN;
	if (localFlitOutFifos_0_data_0_dummy2_1$EN)
	  localFlitOutFifos_0_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_0_data_0_dummy2_1$D_IN;
	if (localFlitOutFifos_0_data_0_rl$EN)
	  localFlitOutFifos_0_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_0_data_0_rl$D_IN;
	if (localFlitOutFifos_0_deqP_dummy2_0$EN)
	  localFlitOutFifos_0_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_0_deqP_dummy2_0$D_IN;
	if (localFlitOutFifos_0_deqP_dummy2_1$EN)
	  localFlitOutFifos_0_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_0_deqP_dummy2_1$D_IN;
	if (localFlitOutFifos_0_deqP_rl$EN)
	  localFlitOutFifos_0_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_0_deqP_rl$D_IN;
	if (localFlitOutFifos_0_enqP_dummy2_0$EN)
	  localFlitOutFifos_0_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_0_enqP_dummy2_0$D_IN;
	if (localFlitOutFifos_0_enqP_dummy2_1$EN)
	  localFlitOutFifos_0_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_0_enqP_dummy2_1$D_IN;
	if (localFlitOutFifos_0_enqP_rl$EN)
	  localFlitOutFifos_0_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_0_enqP_rl$D_IN;
	if (localFlitOutFifos_1_data_0_dummy2_0$EN)
	  localFlitOutFifos_1_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_1_data_0_dummy2_0$D_IN;
	if (localFlitOutFifos_1_data_0_dummy2_1$EN)
	  localFlitOutFifos_1_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_1_data_0_dummy2_1$D_IN;
	if (localFlitOutFifos_1_data_0_rl$EN)
	  localFlitOutFifos_1_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_1_data_0_rl$D_IN;
	if (localFlitOutFifos_1_deqP_dummy2_0$EN)
	  localFlitOutFifos_1_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_1_deqP_dummy2_0$D_IN;
	if (localFlitOutFifos_1_deqP_dummy2_1$EN)
	  localFlitOutFifos_1_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_1_deqP_dummy2_1$D_IN;
	if (localFlitOutFifos_1_deqP_rl$EN)
	  localFlitOutFifos_1_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_1_deqP_rl$D_IN;
	if (localFlitOutFifos_1_enqP_dummy2_0$EN)
	  localFlitOutFifos_1_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_1_enqP_dummy2_0$D_IN;
	if (localFlitOutFifos_1_enqP_dummy2_1$EN)
	  localFlitOutFifos_1_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_1_enqP_dummy2_1$D_IN;
	if (localFlitOutFifos_1_enqP_rl$EN)
	  localFlitOutFifos_1_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_1_enqP_rl$D_IN;
	if (localFlitOutFifos_2_data_0_dummy2_0$EN)
	  localFlitOutFifos_2_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_2_data_0_dummy2_0$D_IN;
	if (localFlitOutFifos_2_data_0_dummy2_1$EN)
	  localFlitOutFifos_2_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_2_data_0_dummy2_1$D_IN;
	if (localFlitOutFifos_2_data_0_rl$EN)
	  localFlitOutFifos_2_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_2_data_0_rl$D_IN;
	if (localFlitOutFifos_2_deqP_dummy2_0$EN)
	  localFlitOutFifos_2_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_2_deqP_dummy2_0$D_IN;
	if (localFlitOutFifos_2_deqP_dummy2_1$EN)
	  localFlitOutFifos_2_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_2_deqP_dummy2_1$D_IN;
	if (localFlitOutFifos_2_deqP_rl$EN)
	  localFlitOutFifos_2_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_2_deqP_rl$D_IN;
	if (localFlitOutFifos_2_enqP_dummy2_0$EN)
	  localFlitOutFifos_2_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_2_enqP_dummy2_0$D_IN;
	if (localFlitOutFifos_2_enqP_dummy2_1$EN)
	  localFlitOutFifos_2_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_2_enqP_dummy2_1$D_IN;
	if (localFlitOutFifos_2_enqP_rl$EN)
	  localFlitOutFifos_2_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitOutFifos_2_enqP_rl$D_IN;
	if (localFlitToHost_data_0_dummy2_0$EN)
	  localFlitToHost_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitToHost_data_0_dummy2_0$D_IN;
	if (localFlitToHost_data_0_dummy2_1$EN)
	  localFlitToHost_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitToHost_data_0_dummy2_1$D_IN;
	if (localFlitToHost_data_0_rl$EN)
	  localFlitToHost_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitToHost_data_0_rl$D_IN;
	if (localFlitToHost_deqP_dummy2_0$EN)
	  localFlitToHost_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitToHost_deqP_dummy2_0$D_IN;
	if (localFlitToHost_deqP_dummy2_1$EN)
	  localFlitToHost_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitToHost_deqP_dummy2_1$D_IN;
	if (localFlitToHost_deqP_rl$EN)
	  localFlitToHost_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitToHost_deqP_rl$D_IN;
	if (localFlitToHost_enqP_dummy2_0$EN)
	  localFlitToHost_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      localFlitToHost_enqP_dummy2_0$D_IN;
	if (localFlitToHost_enqP_dummy2_1$EN)
	  localFlitToHost_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      localFlitToHost_enqP_dummy2_1$D_IN;
	if (localFlitToHost_enqP_rl$EN)
	  localFlitToHost_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      localFlitToHost_enqP_rl$D_IN;
	if (scatterFlitFifo_data_0_dummy2_0$EN)
	  scatterFlitFifo_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_data_0_dummy2_0$D_IN;
	if (scatterFlitFifo_data_0_dummy2_1$EN)
	  scatterFlitFifo_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_data_0_dummy2_1$D_IN;
	if (scatterFlitFifo_data_0_rl$EN)
	  scatterFlitFifo_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_data_0_rl$D_IN;
	if (scatterFlitFifo_deqP_dummy2_0$EN)
	  scatterFlitFifo_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_deqP_dummy2_0$D_IN;
	if (scatterFlitFifo_deqP_dummy2_1$EN)
	  scatterFlitFifo_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_deqP_dummy2_1$D_IN;
	if (scatterFlitFifo_deqP_rl$EN)
	  scatterFlitFifo_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_deqP_rl$D_IN;
	if (scatterFlitFifo_enqP_dummy2_0$EN)
	  scatterFlitFifo_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_enqP_dummy2_0$D_IN;
	if (scatterFlitFifo_enqP_dummy2_1$EN)
	  scatterFlitFifo_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_enqP_dummy2_1$D_IN;
	if (scatterFlitFifo_enqP_rl$EN)
	  scatterFlitFifo_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_enqP_rl$D_IN;
      end
    if (peID$EN) peID <= `BSV_ASSIGNMENT_DELAY peID$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    controlSignal = 2'h2;
    deqBits_0_dummy2_0 = 1'h0;
    deqBits_0_dummy2_1 = 1'h0;
    deqBits_0_dummy2_2 = 1'h0;
    deqBits_0_rl = 1'h0;
    deqBits_1_dummy2_0 = 1'h0;
    deqBits_1_dummy2_1 = 1'h0;
    deqBits_1_dummy2_2 = 1'h0;
    deqBits_1_rl = 1'h0;
    deqBits_2_dummy2_0 = 1'h0;
    deqBits_2_dummy2_1 = 1'h0;
    deqBits_2_dummy2_2 = 1'h0;
    deqBits_2_rl = 1'h0;
    gatherFlitFifo_data_0_dummy2_0 = 1'h0;
    gatherFlitFifo_data_0_dummy2_1 = 1'h0;
    gatherFlitFifo_data_0_rl = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    gatherFlitFifo_deqP_dummy2_0 = 1'h0;
    gatherFlitFifo_deqP_dummy2_1 = 1'h0;
    gatherFlitFifo_deqP_rl = 2'h2;
    gatherFlitFifo_enqP_dummy2_0 = 1'h0;
    gatherFlitFifo_enqP_dummy2_1 = 1'h0;
    gatherFlitFifo_enqP_rl = 2'h2;
    inited = 1'h0;
    localFlitInFifos_0_data_0_dummy2_0 = 1'h0;
    localFlitInFifos_0_data_0_dummy2_1 = 1'h0;
    localFlitInFifos_0_data_0_rl = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    localFlitInFifos_0_deqP_dummy2_0 = 1'h0;
    localFlitInFifos_0_deqP_dummy2_1 = 1'h0;
    localFlitInFifos_0_deqP_rl = 2'h2;
    localFlitInFifos_0_enqP_dummy2_0 = 1'h0;
    localFlitInFifos_0_enqP_dummy2_1 = 1'h0;
    localFlitInFifos_0_enqP_rl = 2'h2;
    localFlitInFifos_1_data_0_dummy2_0 = 1'h0;
    localFlitInFifos_1_data_0_dummy2_1 = 1'h0;
    localFlitInFifos_1_data_0_rl = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    localFlitInFifos_1_deqP_dummy2_0 = 1'h0;
    localFlitInFifos_1_deqP_dummy2_1 = 1'h0;
    localFlitInFifos_1_deqP_rl = 2'h2;
    localFlitInFifos_1_enqP_dummy2_0 = 1'h0;
    localFlitInFifos_1_enqP_dummy2_1 = 1'h0;
    localFlitInFifos_1_enqP_rl = 2'h2;
    localFlitInFifos_2_data_0_dummy2_0 = 1'h0;
    localFlitInFifos_2_data_0_dummy2_1 = 1'h0;
    localFlitInFifos_2_data_0_rl = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    localFlitInFifos_2_deqP_dummy2_0 = 1'h0;
    localFlitInFifos_2_deqP_dummy2_1 = 1'h0;
    localFlitInFifos_2_deqP_rl = 2'h2;
    localFlitInFifos_2_enqP_dummy2_0 = 1'h0;
    localFlitInFifos_2_enqP_dummy2_1 = 1'h0;
    localFlitInFifos_2_enqP_rl = 2'h2;
    localFlitOutFifos_0_data_0_dummy2_0 = 1'h0;
    localFlitOutFifos_0_data_0_dummy2_1 = 1'h0;
    localFlitOutFifos_0_data_0_rl = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    localFlitOutFifos_0_deqP_dummy2_0 = 1'h0;
    localFlitOutFifos_0_deqP_dummy2_1 = 1'h0;
    localFlitOutFifos_0_deqP_rl = 2'h2;
    localFlitOutFifos_0_enqP_dummy2_0 = 1'h0;
    localFlitOutFifos_0_enqP_dummy2_1 = 1'h0;
    localFlitOutFifos_0_enqP_rl = 2'h2;
    localFlitOutFifos_1_data_0_dummy2_0 = 1'h0;
    localFlitOutFifos_1_data_0_dummy2_1 = 1'h0;
    localFlitOutFifos_1_data_0_rl = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    localFlitOutFifos_1_deqP_dummy2_0 = 1'h0;
    localFlitOutFifos_1_deqP_dummy2_1 = 1'h0;
    localFlitOutFifos_1_deqP_rl = 2'h2;
    localFlitOutFifos_1_enqP_dummy2_0 = 1'h0;
    localFlitOutFifos_1_enqP_dummy2_1 = 1'h0;
    localFlitOutFifos_1_enqP_rl = 2'h2;
    localFlitOutFifos_2_data_0_dummy2_0 = 1'h0;
    localFlitOutFifos_2_data_0_dummy2_1 = 1'h0;
    localFlitOutFifos_2_data_0_rl = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    localFlitOutFifos_2_deqP_dummy2_0 = 1'h0;
    localFlitOutFifos_2_deqP_dummy2_1 = 1'h0;
    localFlitOutFifos_2_deqP_rl = 2'h2;
    localFlitOutFifos_2_enqP_dummy2_0 = 1'h0;
    localFlitOutFifos_2_enqP_dummy2_1 = 1'h0;
    localFlitOutFifos_2_enqP_rl = 2'h2;
    localFlitToHost_data_0_dummy2_0 = 1'h0;
    localFlitToHost_data_0_dummy2_1 = 1'h0;
    localFlitToHost_data_0_rl = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    localFlitToHost_deqP_dummy2_0 = 1'h0;
    localFlitToHost_deqP_dummy2_1 = 1'h0;
    localFlitToHost_deqP_rl = 2'h2;
    localFlitToHost_enqP_dummy2_0 = 1'h0;
    localFlitToHost_enqP_dummy2_1 = 1'h0;
    localFlitToHost_enqP_rl = 2'h2;
    peID = 7'h2A;
    scatterFlitFifo_data_0_dummy2_0 = 1'h0;
    scatterFlitFifo_data_0_dummy2_1 = 1'h0;
    scatterFlitFifo_data_0_rl = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    scatterFlitFifo_deqP_dummy2_0 = 1'h0;
    scatterFlitFifo_deqP_dummy2_1 = 1'h0;
    scatterFlitFifo_deqP_rl = 2'h2;
    scatterFlitFifo_enqP_dummy2_0 = 1'h0;
    scatterFlitFifo_enqP_dummy2_1 = 1'h0;
    scatterFlitFifo_enqP_rl = 2'h2;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkBottomSwitch

