//
// Generated by Bluespec Compiler, version 2015.09.beta2 (build 34689, 2015-09-07)
//
// On Mon Sep 11 20:06:26 EDT 2017
//
//
// Ports:
// Name                         I/O  size props
// RDY_scatterInPort_putFlit      O     1
// scatterOutPort_0_getFlit       O    91
// RDY_scatterOutPort_0_getFlit   O     1
// scatterOutPort_1_getFlit       O    91
// RDY_scatterOutPort_1_getFlit   O     1
// RDY_gatherInPort_putFlit       O     1
// gatherOutPort_getFlit          O    91
// RDY_gatherOutPort_getFlit      O     1
// RDY_configureSwitch            O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// scatterInPort_putFlit_flit     I    91
// gatherInPort_putFlit_flit      I    91
// configureSwitch_newControlSignal  I     2 reg
// EN_scatterInPort_putFlit       I     1
// EN_gatherInPort_putFlit        I     1
// EN_configureSwitch             I     1
// EN_scatterOutPort_0_getFlit    I     1 unused
// EN_scatterOutPort_1_getFlit    I     1 unused
// EN_gatherOutPort_getFlit       I     1
//
// Combinational paths from inputs to outputs:
//   (scatterInPort_putFlit_flit,
//    EN_scatterInPort_putFlit) -> scatterOutPort_0_getFlit
//   (scatterInPort_putFlit_flit,
//    EN_scatterInPort_putFlit) -> scatterOutPort_1_getFlit
//   (gatherInPort_putFlit_flit,
//    EN_gatherInPort_putFlit) -> gatherOutPort_getFlit
//   EN_scatterInPort_putFlit -> RDY_scatterOutPort_0_getFlit
//   EN_scatterInPort_putFlit -> RDY_scatterOutPort_1_getFlit
//   EN_gatherInPort_putFlit -> RDY_gatherOutPort_getFlit
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMiddleSwitch(CLK,
		      RST_N,

		      scatterInPort_putFlit_flit,
		      EN_scatterInPort_putFlit,
		      RDY_scatterInPort_putFlit,

		      EN_scatterOutPort_0_getFlit,
		      scatterOutPort_0_getFlit,
		      RDY_scatterOutPort_0_getFlit,

		      EN_scatterOutPort_1_getFlit,
		      scatterOutPort_1_getFlit,
		      RDY_scatterOutPort_1_getFlit,

		      gatherInPort_putFlit_flit,
		      EN_gatherInPort_putFlit,
		      RDY_gatherInPort_putFlit,

		      EN_gatherOutPort_getFlit,
		      gatherOutPort_getFlit,
		      RDY_gatherOutPort_getFlit,

		      configureSwitch_newControlSignal,
		      EN_configureSwitch,
		      RDY_configureSwitch);
  input  CLK;
  input  RST_N;

  // action method scatterInPort_putFlit
  input  [90 : 0] scatterInPort_putFlit_flit;
  input  EN_scatterInPort_putFlit;
  output RDY_scatterInPort_putFlit;

  // actionvalue method scatterOutPort_0_getFlit
  input  EN_scatterOutPort_0_getFlit;
  output [90 : 0] scatterOutPort_0_getFlit;
  output RDY_scatterOutPort_0_getFlit;

  // actionvalue method scatterOutPort_1_getFlit
  input  EN_scatterOutPort_1_getFlit;
  output [90 : 0] scatterOutPort_1_getFlit;
  output RDY_scatterOutPort_1_getFlit;

  // action method gatherInPort_putFlit
  input  [90 : 0] gatherInPort_putFlit_flit;
  input  EN_gatherInPort_putFlit;
  output RDY_gatherInPort_putFlit;

  // actionvalue method gatherOutPort_getFlit
  input  EN_gatherOutPort_getFlit;
  output [90 : 0] gatherOutPort_getFlit;
  output RDY_gatherOutPort_getFlit;

  // action method configureSwitch
  input  [1 : 0] configureSwitch_newControlSignal;
  input  EN_configureSwitch;
  output RDY_configureSwitch;

  // signals for module outputs
  wire [90 : 0] gatherOutPort_getFlit,
		scatterOutPort_0_getFlit,
		scatterOutPort_1_getFlit;
  wire RDY_configureSwitch,
       RDY_gatherInPort_putFlit,
       RDY_gatherOutPort_getFlit,
       RDY_scatterInPort_putFlit,
       RDY_scatterOutPort_0_getFlit,
       RDY_scatterOutPort_1_getFlit;

  // register controlSignal
  reg [1 : 0] controlSignal;
  wire [1 : 0] controlSignal$D_IN;
  wire controlSignal$EN;

  // register gatherFlitFifo_data_0_dummy2_0
  reg gatherFlitFifo_data_0_dummy2_0;
  wire gatherFlitFifo_data_0_dummy2_0$D_IN, gatherFlitFifo_data_0_dummy2_0$EN;

  // register gatherFlitFifo_data_0_dummy2_1
  reg gatherFlitFifo_data_0_dummy2_1;
  wire gatherFlitFifo_data_0_dummy2_1$D_IN, gatherFlitFifo_data_0_dummy2_1$EN;

  // register gatherFlitFifo_data_0_rl
  reg [90 : 0] gatherFlitFifo_data_0_rl;
  wire [90 : 0] gatherFlitFifo_data_0_rl$D_IN;
  wire gatherFlitFifo_data_0_rl$EN;

  // register gatherFlitFifo_deqP_dummy2_0
  reg gatherFlitFifo_deqP_dummy2_0;
  wire gatherFlitFifo_deqP_dummy2_0$D_IN, gatherFlitFifo_deqP_dummy2_0$EN;

  // register gatherFlitFifo_deqP_dummy2_1
  reg gatherFlitFifo_deqP_dummy2_1;
  wire gatherFlitFifo_deqP_dummy2_1$D_IN, gatherFlitFifo_deqP_dummy2_1$EN;

  // register gatherFlitFifo_deqP_rl
  reg [1 : 0] gatherFlitFifo_deqP_rl;
  wire [1 : 0] gatherFlitFifo_deqP_rl$D_IN;
  wire gatherFlitFifo_deqP_rl$EN;

  // register gatherFlitFifo_enqP_dummy2_0
  reg gatherFlitFifo_enqP_dummy2_0;
  wire gatherFlitFifo_enqP_dummy2_0$D_IN, gatherFlitFifo_enqP_dummy2_0$EN;

  // register gatherFlitFifo_enqP_dummy2_1
  reg gatherFlitFifo_enqP_dummy2_1;
  wire gatherFlitFifo_enqP_dummy2_1$D_IN, gatherFlitFifo_enqP_dummy2_1$EN;

  // register gatherFlitFifo_enqP_rl
  reg [1 : 0] gatherFlitFifo_enqP_rl;
  wire [1 : 0] gatherFlitFifo_enqP_rl$D_IN;
  wire gatherFlitFifo_enqP_rl$EN;

  // register scatterFlitFifo_data_0_dummy2_0
  reg scatterFlitFifo_data_0_dummy2_0;
  wire scatterFlitFifo_data_0_dummy2_0$D_IN,
       scatterFlitFifo_data_0_dummy2_0$EN;

  // register scatterFlitFifo_data_0_dummy2_1
  reg scatterFlitFifo_data_0_dummy2_1;
  wire scatterFlitFifo_data_0_dummy2_1$D_IN,
       scatterFlitFifo_data_0_dummy2_1$EN;

  // register scatterFlitFifo_data_0_rl
  reg [90 : 0] scatterFlitFifo_data_0_rl;
  wire [90 : 0] scatterFlitFifo_data_0_rl$D_IN;
  wire scatterFlitFifo_data_0_rl$EN;

  // register scatterFlitFifo_deqP_dummy2_0
  reg scatterFlitFifo_deqP_dummy2_0;
  wire scatterFlitFifo_deqP_dummy2_0$D_IN, scatterFlitFifo_deqP_dummy2_0$EN;

  // register scatterFlitFifo_deqP_dummy2_1
  reg scatterFlitFifo_deqP_dummy2_1;
  wire scatterFlitFifo_deqP_dummy2_1$D_IN, scatterFlitFifo_deqP_dummy2_1$EN;

  // register scatterFlitFifo_deqP_rl
  reg [1 : 0] scatterFlitFifo_deqP_rl;
  wire [1 : 0] scatterFlitFifo_deqP_rl$D_IN;
  wire scatterFlitFifo_deqP_rl$EN;

  // register scatterFlitFifo_enqP_dummy2_0
  reg scatterFlitFifo_enqP_dummy2_0;
  wire scatterFlitFifo_enqP_dummy2_0$D_IN, scatterFlitFifo_enqP_dummy2_0$EN;

  // register scatterFlitFifo_enqP_dummy2_1
  reg scatterFlitFifo_enqP_dummy2_1;
  wire scatterFlitFifo_enqP_dummy2_1$D_IN, scatterFlitFifo_enqP_dummy2_1$EN;

  // register scatterFlitFifo_enqP_rl
  reg [1 : 0] scatterFlitFifo_enqP_rl;
  wire [1 : 0] scatterFlitFifo_enqP_rl$D_IN;
  wire scatterFlitFifo_enqP_rl$EN;

  // remaining internal signals
  wire [1 : 0] cnt1__h3360,
	       cnt1__h6659,
	       gatherFlitFifo_deqP_rl_PLUS_1__q2,
	       gatherFlitFifo_enqP_rl_PLUS_1__q1,
	       n__read__h6726,
	       n__read__h9034,
	       scatterFlitFifo_deqP_rl_PLUS_1__q4,
	       scatterFlitFifo_enqP_rl_PLUS_1__q3,
	       upd__h3314,
	       upd__h6613,
	       upd__h6854,
	       upd__h9087;

  // action method scatterInPort_putFlit
  assign RDY_scatterInPort_putFlit =
	     ((scatterFlitFifo_enqP_rl < scatterFlitFifo_deqP_rl) ?
		2'd1 :
		scatterFlitFifo_enqP_rl - scatterFlitFifo_deqP_rl) ==
	     2'd0 ;

  // actionvalue method scatterOutPort_0_getFlit
  assign scatterOutPort_0_getFlit = scatterOutPort_1_getFlit ;
  assign RDY_scatterOutPort_0_getFlit =
	     cnt1__h6659 != 2'd0 && controlSignal[1] ;

  // actionvalue method scatterOutPort_1_getFlit
  assign scatterOutPort_1_getFlit =
	     EN_scatterInPort_putFlit ?
	       scatterInPort_putFlit_flit :
	       scatterFlitFifo_data_0_rl ;
  assign RDY_scatterOutPort_1_getFlit =
	     cnt1__h6659 != 2'd0 && controlSignal[0] ;

  // action method gatherInPort_putFlit
  assign RDY_gatherInPort_putFlit =
	     ((gatherFlitFifo_enqP_rl < gatherFlitFifo_deqP_rl) ?
		2'd1 :
		gatherFlitFifo_enqP_rl - gatherFlitFifo_deqP_rl) ==
	     2'd0 ;

  // actionvalue method gatherOutPort_getFlit
  assign gatherOutPort_getFlit =
	     EN_gatherInPort_putFlit ?
	       gatherInPort_putFlit_flit :
	       gatherFlitFifo_data_0_rl ;
  assign RDY_gatherOutPort_getFlit = cnt1__h3360 != 2'd0 ;

  // action method configureSwitch
  assign RDY_configureSwitch = 1'd1 ;

  // register controlSignal
  assign controlSignal$D_IN = configureSwitch_newControlSignal ;
  assign controlSignal$EN = EN_configureSwitch ;

  // register gatherFlitFifo_data_0_dummy2_0
  assign gatherFlitFifo_data_0_dummy2_0$D_IN = 1'd1 ;
  assign gatherFlitFifo_data_0_dummy2_0$EN = EN_gatherInPort_putFlit ;

  // register gatherFlitFifo_data_0_dummy2_1
  assign gatherFlitFifo_data_0_dummy2_1$D_IN = 1'b0 ;
  assign gatherFlitFifo_data_0_dummy2_1$EN = 1'b0 ;

  // register gatherFlitFifo_data_0_rl
  assign gatherFlitFifo_data_0_rl$D_IN =
	     EN_gatherInPort_putFlit ?
	       gatherInPort_putFlit_flit :
	       gatherFlitFifo_data_0_rl ;
  assign gatherFlitFifo_data_0_rl$EN = 1'd1 ;

  // register gatherFlitFifo_deqP_dummy2_0
  assign gatherFlitFifo_deqP_dummy2_0$D_IN = 1'd1 ;
  assign gatherFlitFifo_deqP_dummy2_0$EN = EN_gatherOutPort_getFlit ;

  // register gatherFlitFifo_deqP_dummy2_1
  assign gatherFlitFifo_deqP_dummy2_1$D_IN = 1'b0 ;
  assign gatherFlitFifo_deqP_dummy2_1$EN = 1'b0 ;

  // register gatherFlitFifo_deqP_rl
  assign gatherFlitFifo_deqP_rl$D_IN =
	     EN_gatherOutPort_getFlit ? upd__h3314 : gatherFlitFifo_deqP_rl ;
  assign gatherFlitFifo_deqP_rl$EN = 1'd1 ;

  // register gatherFlitFifo_enqP_dummy2_0
  assign gatherFlitFifo_enqP_dummy2_0$D_IN = 1'd1 ;
  assign gatherFlitFifo_enqP_dummy2_0$EN = EN_gatherInPort_putFlit ;

  // register gatherFlitFifo_enqP_dummy2_1
  assign gatherFlitFifo_enqP_dummy2_1$D_IN = 1'b0 ;
  assign gatherFlitFifo_enqP_dummy2_1$EN = 1'b0 ;

  // register gatherFlitFifo_enqP_rl
  assign gatherFlitFifo_enqP_rl$D_IN = n__read__h9034 ;
  assign gatherFlitFifo_enqP_rl$EN = 1'd1 ;

  // register scatterFlitFifo_data_0_dummy2_0
  assign scatterFlitFifo_data_0_dummy2_0$D_IN = 1'd1 ;
  assign scatterFlitFifo_data_0_dummy2_0$EN = EN_scatterInPort_putFlit ;

  // register scatterFlitFifo_data_0_dummy2_1
  assign scatterFlitFifo_data_0_dummy2_1$D_IN = 1'b0 ;
  assign scatterFlitFifo_data_0_dummy2_1$EN = 1'b0 ;

  // register scatterFlitFifo_data_0_rl
  assign scatterFlitFifo_data_0_rl$D_IN = scatterOutPort_1_getFlit ;
  assign scatterFlitFifo_data_0_rl$EN = 1'd1 ;

  // register scatterFlitFifo_deqP_dummy2_0
  assign scatterFlitFifo_deqP_dummy2_0$D_IN = 1'd1 ;
  assign scatterFlitFifo_deqP_dummy2_0$EN = cnt1__h6659 != 2'd0 ;

  // register scatterFlitFifo_deqP_dummy2_1
  assign scatterFlitFifo_deqP_dummy2_1$D_IN = 1'b0 ;
  assign scatterFlitFifo_deqP_dummy2_1$EN = 1'b0 ;

  // register scatterFlitFifo_deqP_rl
  assign scatterFlitFifo_deqP_rl$D_IN =
	     (cnt1__h6659 != 2'd0) ? upd__h6613 : scatterFlitFifo_deqP_rl ;
  assign scatterFlitFifo_deqP_rl$EN = 1'd1 ;

  // register scatterFlitFifo_enqP_dummy2_0
  assign scatterFlitFifo_enqP_dummy2_0$D_IN = 1'd1 ;
  assign scatterFlitFifo_enqP_dummy2_0$EN = EN_scatterInPort_putFlit ;

  // register scatterFlitFifo_enqP_dummy2_1
  assign scatterFlitFifo_enqP_dummy2_1$D_IN = 1'b0 ;
  assign scatterFlitFifo_enqP_dummy2_1$EN = 1'b0 ;

  // register scatterFlitFifo_enqP_rl
  assign scatterFlitFifo_enqP_rl$D_IN = n__read__h6726 ;
  assign scatterFlitFifo_enqP_rl$EN = 1'd1 ;

  // remaining internal signals
  assign cnt1__h3360 =
	     (n__read__h9034 < gatherFlitFifo_deqP_rl) ?
	       2'd1 :
	       n__read__h9034 - gatherFlitFifo_deqP_rl ;
  assign cnt1__h6659 =
	     (n__read__h6726 < scatterFlitFifo_deqP_rl) ?
	       2'd1 :
	       n__read__h6726 - scatterFlitFifo_deqP_rl ;
  assign gatherFlitFifo_deqP_rl_PLUS_1__q2 = gatherFlitFifo_deqP_rl + 2'd1 ;
  assign gatherFlitFifo_enqP_rl_PLUS_1__q1 = gatherFlitFifo_enqP_rl + 2'd1 ;
  assign n__read__h6726 =
	     EN_scatterInPort_putFlit ? upd__h6854 : scatterFlitFifo_enqP_rl ;
  assign n__read__h9034 =
	     EN_gatherInPort_putFlit ? upd__h9087 : gatherFlitFifo_enqP_rl ;
  assign scatterFlitFifo_deqP_rl_PLUS_1__q4 = scatterFlitFifo_deqP_rl + 2'd1 ;
  assign scatterFlitFifo_enqP_rl_PLUS_1__q3 = scatterFlitFifo_enqP_rl + 2'd1 ;
  assign upd__h3314 = { 1'd0, gatherFlitFifo_deqP_rl_PLUS_1__q2[0] } ;
  assign upd__h6613 = { 1'd0, scatterFlitFifo_deqP_rl_PLUS_1__q4[0] } ;
  assign upd__h6854 = { 1'd0, scatterFlitFifo_enqP_rl_PLUS_1__q3[0] } ;
  assign upd__h9087 = { 1'd0, gatherFlitFifo_enqP_rl_PLUS_1__q1[0] } ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        controlSignal <= `BSV_ASSIGNMENT_DELAY 2'd0;
	gatherFlitFifo_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherFlitFifo_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherFlitFifo_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	    91'h2AAAAAAAAAAAAAAAAAAAAAA;
	gatherFlitFifo_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherFlitFifo_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherFlitFifo_deqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	gatherFlitFifo_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherFlitFifo_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherFlitFifo_enqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	scatterFlitFifo_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFlitFifo_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFlitFifo_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	    91'h2AAAAAAAAAAAAAAAAAAAAAA;
	scatterFlitFifo_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFlitFifo_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFlitFifo_deqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	scatterFlitFifo_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFlitFifo_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFlitFifo_enqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
      end
    else
      begin
        if (controlSignal$EN)
	  controlSignal <= `BSV_ASSIGNMENT_DELAY controlSignal$D_IN;
	if (gatherFlitFifo_data_0_dummy2_0$EN)
	  gatherFlitFifo_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_data_0_dummy2_0$D_IN;
	if (gatherFlitFifo_data_0_dummy2_1$EN)
	  gatherFlitFifo_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_data_0_dummy2_1$D_IN;
	if (gatherFlitFifo_data_0_rl$EN)
	  gatherFlitFifo_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_data_0_rl$D_IN;
	if (gatherFlitFifo_deqP_dummy2_0$EN)
	  gatherFlitFifo_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_deqP_dummy2_0$D_IN;
	if (gatherFlitFifo_deqP_dummy2_1$EN)
	  gatherFlitFifo_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_deqP_dummy2_1$D_IN;
	if (gatherFlitFifo_deqP_rl$EN)
	  gatherFlitFifo_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_deqP_rl$D_IN;
	if (gatherFlitFifo_enqP_dummy2_0$EN)
	  gatherFlitFifo_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_enqP_dummy2_0$D_IN;
	if (gatherFlitFifo_enqP_dummy2_1$EN)
	  gatherFlitFifo_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_enqP_dummy2_1$D_IN;
	if (gatherFlitFifo_enqP_rl$EN)
	  gatherFlitFifo_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      gatherFlitFifo_enqP_rl$D_IN;
	if (scatterFlitFifo_data_0_dummy2_0$EN)
	  scatterFlitFifo_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_data_0_dummy2_0$D_IN;
	if (scatterFlitFifo_data_0_dummy2_1$EN)
	  scatterFlitFifo_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_data_0_dummy2_1$D_IN;
	if (scatterFlitFifo_data_0_rl$EN)
	  scatterFlitFifo_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_data_0_rl$D_IN;
	if (scatterFlitFifo_deqP_dummy2_0$EN)
	  scatterFlitFifo_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_deqP_dummy2_0$D_IN;
	if (scatterFlitFifo_deqP_dummy2_1$EN)
	  scatterFlitFifo_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_deqP_dummy2_1$D_IN;
	if (scatterFlitFifo_deqP_rl$EN)
	  scatterFlitFifo_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_deqP_rl$D_IN;
	if (scatterFlitFifo_enqP_dummy2_0$EN)
	  scatterFlitFifo_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_enqP_dummy2_0$D_IN;
	if (scatterFlitFifo_enqP_dummy2_1$EN)
	  scatterFlitFifo_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_enqP_dummy2_1$D_IN;
	if (scatterFlitFifo_enqP_rl$EN)
	  scatterFlitFifo_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      scatterFlitFifo_enqP_rl$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    controlSignal = 2'h2;
    gatherFlitFifo_data_0_dummy2_0 = 1'h0;
    gatherFlitFifo_data_0_dummy2_1 = 1'h0;
    gatherFlitFifo_data_0_rl = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    gatherFlitFifo_deqP_dummy2_0 = 1'h0;
    gatherFlitFifo_deqP_dummy2_1 = 1'h0;
    gatherFlitFifo_deqP_rl = 2'h2;
    gatherFlitFifo_enqP_dummy2_0 = 1'h0;
    gatherFlitFifo_enqP_dummy2_1 = 1'h0;
    gatherFlitFifo_enqP_rl = 2'h2;
    scatterFlitFifo_data_0_dummy2_0 = 1'h0;
    scatterFlitFifo_data_0_dummy2_1 = 1'h0;
    scatterFlitFifo_data_0_rl = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    scatterFlitFifo_deqP_dummy2_0 = 1'h0;
    scatterFlitFifo_deqP_dummy2_1 = 1'h0;
    scatterFlitFifo_deqP_rl = 2'h2;
    scatterFlitFifo_enqP_dummy2_0 = 1'h0;
    scatterFlitFifo_enqP_dummy2_1 = 1'h0;
    scatterFlitFifo_enqP_rl = 2'h2;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkMiddleSwitch

