//
// Generated by Bluespec Compiler, version 2015.09.beta2 (build 34689, 2015-09-07)
//
// On Mon Sep 11 20:06:25 EDT 2017
//
//
// Ports:
// Name                         I/O  size props
// RDY_gatherInPort_0_putFlit     O     1
// RDY_gatherInPort_1_putFlit     O     1
// RDY_gatherInPort_2_putFlit     O     1
// gatherOutPort_getFlit          O    91
// RDY_gatherOutPort_getFlit      O     1
// RDY_scatterInPort_putFlit      O     1
// scatterOutPort_0_getFlit       O    91
// RDY_scatterOutPort_0_getFlit   O     1
// scatterOutPort_1_getFlit       O    91
// RDY_scatterOutPort_1_getFlit   O     1
// RDY_configureSwitch            O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// gatherInPort_0_putFlit_flit    I    91 reg
// gatherInPort_1_putFlit_flit    I    91 reg
// gatherInPort_2_putFlit_flit    I    91 reg
// scatterInPort_putFlit_flit     I    91
// configureSwitch_newControlSignal  I     2 reg
// EN_gatherInPort_0_putFlit      I     1
// EN_gatherInPort_1_putFlit      I     1
// EN_gatherInPort_2_putFlit      I     1
// EN_scatterInPort_putFlit       I     1
// EN_configureSwitch             I     1
// EN_gatherOutPort_getFlit       I     1
// EN_scatterOutPort_0_getFlit    I     1
// EN_scatterOutPort_1_getFlit    I     1
//
// Combinational paths from inputs to outputs:
//   (scatterInPort_putFlit_flit,
//    EN_scatterInPort_putFlit) -> scatterOutPort_0_getFlit
//   (scatterInPort_putFlit_flit,
//    EN_scatterInPort_putFlit) -> scatterOutPort_1_getFlit
//   EN_scatterInPort_putFlit -> RDY_scatterOutPort_0_getFlit
//   EN_scatterInPort_putFlit -> RDY_scatterOutPort_1_getFlit
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTopSwitch(CLK,
		   RST_N,

		   gatherInPort_0_putFlit_flit,
		   EN_gatherInPort_0_putFlit,
		   RDY_gatherInPort_0_putFlit,

		   gatherInPort_1_putFlit_flit,
		   EN_gatherInPort_1_putFlit,
		   RDY_gatherInPort_1_putFlit,

		   gatherInPort_2_putFlit_flit,
		   EN_gatherInPort_2_putFlit,
		   RDY_gatherInPort_2_putFlit,

		   EN_gatherOutPort_getFlit,
		   gatherOutPort_getFlit,
		   RDY_gatherOutPort_getFlit,

		   scatterInPort_putFlit_flit,
		   EN_scatterInPort_putFlit,
		   RDY_scatterInPort_putFlit,

		   EN_scatterOutPort_0_getFlit,
		   scatterOutPort_0_getFlit,
		   RDY_scatterOutPort_0_getFlit,

		   EN_scatterOutPort_1_getFlit,
		   scatterOutPort_1_getFlit,
		   RDY_scatterOutPort_1_getFlit,

		   configureSwitch_newControlSignal,
		   EN_configureSwitch,
		   RDY_configureSwitch);
  input  CLK;
  input  RST_N;

  // action method gatherInPort_0_putFlit
  input  [90 : 0] gatherInPort_0_putFlit_flit;
  input  EN_gatherInPort_0_putFlit;
  output RDY_gatherInPort_0_putFlit;

  // action method gatherInPort_1_putFlit
  input  [90 : 0] gatherInPort_1_putFlit_flit;
  input  EN_gatherInPort_1_putFlit;
  output RDY_gatherInPort_1_putFlit;

  // action method gatherInPort_2_putFlit
  input  [90 : 0] gatherInPort_2_putFlit_flit;
  input  EN_gatherInPort_2_putFlit;
  output RDY_gatherInPort_2_putFlit;

  // actionvalue method gatherOutPort_getFlit
  input  EN_gatherOutPort_getFlit;
  output [90 : 0] gatherOutPort_getFlit;
  output RDY_gatherOutPort_getFlit;

  // action method scatterInPort_putFlit
  input  [90 : 0] scatterInPort_putFlit_flit;
  input  EN_scatterInPort_putFlit;
  output RDY_scatterInPort_putFlit;

  // actionvalue method scatterOutPort_0_getFlit
  input  EN_scatterOutPort_0_getFlit;
  output [90 : 0] scatterOutPort_0_getFlit;
  output RDY_scatterOutPort_0_getFlit;

  // actionvalue method scatterOutPort_1_getFlit
  input  EN_scatterOutPort_1_getFlit;
  output [90 : 0] scatterOutPort_1_getFlit;
  output RDY_scatterOutPort_1_getFlit;

  // action method configureSwitch
  input  [1 : 0] configureSwitch_newControlSignal;
  input  EN_configureSwitch;
  output RDY_configureSwitch;

  // signals for module outputs
  wire [90 : 0] gatherOutPort_getFlit,
		scatterOutPort_0_getFlit,
		scatterOutPort_1_getFlit;
  wire RDY_configureSwitch,
       RDY_gatherInPort_0_putFlit,
       RDY_gatherInPort_1_putFlit,
       RDY_gatherInPort_2_putFlit,
       RDY_gatherOutPort_getFlit,
       RDY_scatterInPort_putFlit,
       RDY_scatterOutPort_0_getFlit,
       RDY_scatterOutPort_1_getFlit;

  // inlined wires
  wire [90 : 0] gatherOutFifo_data_0_lat_0$wget;
  wire gatherInFifos_0_deqP_lat_0$whas,
       gatherInFifos_1_deqP_lat_0$whas,
       gatherInFifos_2_deqP_lat_0$whas,
       gatherOutFifo_data_0_lat_0$whas,
       isSent_lat_2$whas;

  // register controlSignal
  reg [1 : 0] controlSignal;
  wire [1 : 0] controlSignal$D_IN;
  wire controlSignal$EN;

  // register gatherInFifos_0_data_0
  reg [90 : 0] gatherInFifos_0_data_0;
  wire [90 : 0] gatherInFifos_0_data_0$D_IN;
  wire gatherInFifos_0_data_0$EN;

  // register gatherInFifos_0_data_1
  reg [90 : 0] gatherInFifos_0_data_1;
  wire [90 : 0] gatherInFifos_0_data_1$D_IN;
  wire gatherInFifos_0_data_1$EN;

  // register gatherInFifos_0_deqP_dummy2_0
  reg gatherInFifos_0_deqP_dummy2_0;
  wire gatherInFifos_0_deqP_dummy2_0$D_IN, gatherInFifos_0_deqP_dummy2_0$EN;

  // register gatherInFifos_0_deqP_dummy2_1
  reg gatherInFifos_0_deqP_dummy2_1;
  wire gatherInFifos_0_deqP_dummy2_1$D_IN, gatherInFifos_0_deqP_dummy2_1$EN;

  // register gatherInFifos_0_deqP_rl
  reg [2 : 0] gatherInFifos_0_deqP_rl;
  wire [2 : 0] gatherInFifos_0_deqP_rl$D_IN;
  wire gatherInFifos_0_deqP_rl$EN;

  // register gatherInFifos_0_enqP_dummy2_0
  reg gatherInFifos_0_enqP_dummy2_0;
  wire gatherInFifos_0_enqP_dummy2_0$D_IN, gatherInFifos_0_enqP_dummy2_0$EN;

  // register gatherInFifos_0_enqP_dummy2_1
  reg gatherInFifos_0_enqP_dummy2_1;
  wire gatherInFifos_0_enqP_dummy2_1$D_IN, gatherInFifos_0_enqP_dummy2_1$EN;

  // register gatherInFifos_0_enqP_rl
  reg [2 : 0] gatherInFifos_0_enqP_rl;
  wire [2 : 0] gatherInFifos_0_enqP_rl$D_IN;
  wire gatherInFifos_0_enqP_rl$EN;

  // register gatherInFifos_1_data_0
  reg [90 : 0] gatherInFifos_1_data_0;
  wire [90 : 0] gatherInFifos_1_data_0$D_IN;
  wire gatherInFifos_1_data_0$EN;

  // register gatherInFifos_1_data_1
  reg [90 : 0] gatherInFifos_1_data_1;
  wire [90 : 0] gatherInFifos_1_data_1$D_IN;
  wire gatherInFifos_1_data_1$EN;

  // register gatherInFifos_1_deqP_dummy2_0
  reg gatherInFifos_1_deqP_dummy2_0;
  wire gatherInFifos_1_deqP_dummy2_0$D_IN, gatherInFifos_1_deqP_dummy2_0$EN;

  // register gatherInFifos_1_deqP_dummy2_1
  reg gatherInFifos_1_deqP_dummy2_1;
  wire gatherInFifos_1_deqP_dummy2_1$D_IN, gatherInFifos_1_deqP_dummy2_1$EN;

  // register gatherInFifos_1_deqP_rl
  reg [2 : 0] gatherInFifos_1_deqP_rl;
  wire [2 : 0] gatherInFifos_1_deqP_rl$D_IN;
  wire gatherInFifos_1_deqP_rl$EN;

  // register gatherInFifos_1_enqP_dummy2_0
  reg gatherInFifos_1_enqP_dummy2_0;
  wire gatherInFifos_1_enqP_dummy2_0$D_IN, gatherInFifos_1_enqP_dummy2_0$EN;

  // register gatherInFifos_1_enqP_dummy2_1
  reg gatherInFifos_1_enqP_dummy2_1;
  wire gatherInFifos_1_enqP_dummy2_1$D_IN, gatherInFifos_1_enqP_dummy2_1$EN;

  // register gatherInFifos_1_enqP_rl
  reg [2 : 0] gatherInFifos_1_enqP_rl;
  wire [2 : 0] gatherInFifos_1_enqP_rl$D_IN;
  wire gatherInFifos_1_enqP_rl$EN;

  // register gatherInFifos_2_data_0
  reg [90 : 0] gatherInFifos_2_data_0;
  wire [90 : 0] gatherInFifos_2_data_0$D_IN;
  wire gatherInFifos_2_data_0$EN;

  // register gatherInFifos_2_data_1
  reg [90 : 0] gatherInFifos_2_data_1;
  wire [90 : 0] gatherInFifos_2_data_1$D_IN;
  wire gatherInFifos_2_data_1$EN;

  // register gatherInFifos_2_deqP_dummy2_0
  reg gatherInFifos_2_deqP_dummy2_0;
  wire gatherInFifos_2_deqP_dummy2_0$D_IN, gatherInFifos_2_deqP_dummy2_0$EN;

  // register gatherInFifos_2_deqP_dummy2_1
  reg gatherInFifos_2_deqP_dummy2_1;
  wire gatherInFifos_2_deqP_dummy2_1$D_IN, gatherInFifos_2_deqP_dummy2_1$EN;

  // register gatherInFifos_2_deqP_rl
  reg [2 : 0] gatherInFifos_2_deqP_rl;
  wire [2 : 0] gatherInFifos_2_deqP_rl$D_IN;
  wire gatherInFifos_2_deqP_rl$EN;

  // register gatherInFifos_2_enqP_dummy2_0
  reg gatherInFifos_2_enqP_dummy2_0;
  wire gatherInFifos_2_enqP_dummy2_0$D_IN, gatherInFifos_2_enqP_dummy2_0$EN;

  // register gatherInFifos_2_enqP_dummy2_1
  reg gatherInFifos_2_enqP_dummy2_1;
  wire gatherInFifos_2_enqP_dummy2_1$D_IN, gatherInFifos_2_enqP_dummy2_1$EN;

  // register gatherInFifos_2_enqP_rl
  reg [2 : 0] gatherInFifos_2_enqP_rl;
  wire [2 : 0] gatherInFifos_2_enqP_rl$D_IN;
  wire gatherInFifos_2_enqP_rl$EN;

  // register gatherOutFifo_data_0_dummy2_0
  reg gatherOutFifo_data_0_dummy2_0;
  wire gatherOutFifo_data_0_dummy2_0$D_IN, gatherOutFifo_data_0_dummy2_0$EN;

  // register gatherOutFifo_data_0_dummy2_1
  reg gatherOutFifo_data_0_dummy2_1;
  wire gatherOutFifo_data_0_dummy2_1$D_IN, gatherOutFifo_data_0_dummy2_1$EN;

  // register gatherOutFifo_data_0_rl
  reg [90 : 0] gatherOutFifo_data_0_rl;
  wire [90 : 0] gatherOutFifo_data_0_rl$D_IN;
  wire gatherOutFifo_data_0_rl$EN;

  // register gatherOutFifo_deqP_dummy2_0
  reg gatherOutFifo_deqP_dummy2_0;
  wire gatherOutFifo_deqP_dummy2_0$D_IN, gatherOutFifo_deqP_dummy2_0$EN;

  // register gatherOutFifo_deqP_dummy2_1
  reg gatherOutFifo_deqP_dummy2_1;
  wire gatherOutFifo_deqP_dummy2_1$D_IN, gatherOutFifo_deqP_dummy2_1$EN;

  // register gatherOutFifo_deqP_rl
  reg [1 : 0] gatherOutFifo_deqP_rl;
  wire [1 : 0] gatherOutFifo_deqP_rl$D_IN;
  wire gatherOutFifo_deqP_rl$EN;

  // register gatherOutFifo_enqP_dummy2_0
  reg gatherOutFifo_enqP_dummy2_0;
  wire gatherOutFifo_enqP_dummy2_0$D_IN, gatherOutFifo_enqP_dummy2_0$EN;

  // register gatherOutFifo_enqP_dummy2_1
  reg gatherOutFifo_enqP_dummy2_1;
  wire gatherOutFifo_enqP_dummy2_1$D_IN, gatherOutFifo_enqP_dummy2_1$EN;

  // register gatherOutFifo_enqP_rl
  reg [1 : 0] gatherOutFifo_enqP_rl;
  wire [1 : 0] gatherOutFifo_enqP_rl$D_IN;
  wire gatherOutFifo_enqP_rl$EN;

  // register isSent_dummy2_0
  reg isSent_dummy2_0;
  wire isSent_dummy2_0$D_IN, isSent_dummy2_0$EN;

  // register isSent_dummy2_1
  reg isSent_dummy2_1;
  wire isSent_dummy2_1$D_IN, isSent_dummy2_1$EN;

  // register isSent_dummy2_2
  reg isSent_dummy2_2;
  wire isSent_dummy2_2$D_IN, isSent_dummy2_2$EN;

  // register isSent_rl
  reg isSent_rl;
  wire isSent_rl$D_IN, isSent_rl$EN;

  // register scatterFifo_data_0_dummy2_0
  reg scatterFifo_data_0_dummy2_0;
  wire scatterFifo_data_0_dummy2_0$D_IN, scatterFifo_data_0_dummy2_0$EN;

  // register scatterFifo_data_0_dummy2_1
  reg scatterFifo_data_0_dummy2_1;
  wire scatterFifo_data_0_dummy2_1$D_IN, scatterFifo_data_0_dummy2_1$EN;

  // register scatterFifo_data_0_rl
  reg [90 : 0] scatterFifo_data_0_rl;
  wire [90 : 0] scatterFifo_data_0_rl$D_IN;
  wire scatterFifo_data_0_rl$EN;

  // register scatterFifo_deqP_dummy2_0
  reg scatterFifo_deqP_dummy2_0;
  wire scatterFifo_deqP_dummy2_0$D_IN, scatterFifo_deqP_dummy2_0$EN;

  // register scatterFifo_deqP_dummy2_1
  reg scatterFifo_deqP_dummy2_1;
  wire scatterFifo_deqP_dummy2_1$D_IN, scatterFifo_deqP_dummy2_1$EN;

  // register scatterFifo_deqP_rl
  reg [1 : 0] scatterFifo_deqP_rl;
  wire [1 : 0] scatterFifo_deqP_rl$D_IN;
  wire scatterFifo_deqP_rl$EN;

  // register scatterFifo_enqP_dummy2_0
  reg scatterFifo_enqP_dummy2_0;
  wire scatterFifo_enqP_dummy2_0$D_IN, scatterFifo_enqP_dummy2_0$EN;

  // register scatterFifo_enqP_dummy2_1
  reg scatterFifo_enqP_dummy2_1;
  wire scatterFifo_enqP_dummy2_1$D_IN, scatterFifo_enqP_dummy2_1$EN;

  // register scatterFifo_enqP_rl
  reg [1 : 0] scatterFifo_enqP_rl;
  wire [1 : 0] scatterFifo_enqP_rl$D_IN;
  wire scatterFifo_enqP_rl$EN;

  // rule scheduling signals
  wire WILL_FIRE_RL_sendGatherFlit;

  // remaining internal signals
  reg [64 : 0] CASE_y6832_0_gatherInFifos_0_data_0_BITS_87_TO_ETC__q20,
	       CASE_y7262_0_gatherInFifos_1_data_0_BITS_87_TO_ETC__q16,
	       CASE_y7692_0_gatherInFifos_2_data_0_BITS_87_TO_ETC__q12;
  reg [15 : 0] CASE_y6832_0_gatherInFifos_0_data_0_BITS_15_TO_ETC__q22,
	       CASE_y7262_0_gatherInFifos_1_data_0_BITS_15_TO_ETC__q18,
	       CASE_y7692_0_gatherInFifos_2_data_0_BITS_15_TO_ETC__q14;
  reg [6 : 0] CASE_y6832_0_gatherInFifos_0_data_0_BITS_22_TO_ETC__q21,
	      CASE_y7262_0_gatherInFifos_1_data_0_BITS_22_TO_ETC__q17,
	      CASE_y7692_0_gatherInFifos_2_data_0_BITS_22_TO_ETC__q13;
  reg [2 : 0] CASE_y6832_0_gatherInFifos_0_data_0_BITS_90_TO_ETC__q19,
	      CASE_y7262_0_gatherInFifos_1_data_0_BITS_90_TO_ETC__q15,
	      CASE_y7692_0_gatherInFifos_2_data_0_BITS_90_TO_ETC__q11;
  wire [90 : 0] SEL_ARR_gatherInFifos_0_data_0_34_BITS_90_TO_8_ETC___d253,
		SEL_ARR_gatherInFifos_1_data_0_13_BITS_90_TO_8_ETC___d232,
		SEL_ARR_gatherInFifos_2_data_0_93_BITS_90_TO_8_ETC___d212;
  wire [2 : 0] cnt0__h10628,
	       cnt0__h12803,
	       cnt0__h14978,
	       cnt1__h10629,
	       cnt1__h12804,
	       cnt1__h14979,
	       gatherInFifos_0_deqP_rl_PLUS_1__q6,
	       gatherInFifos_0_enqP_rl_PLUS_1__q5,
	       gatherInFifos_1_deqP_rl_PLUS_1__q8,
	       gatherInFifos_1_enqP_rl_PLUS_1__q7,
	       gatherInFifos_2_deqP_rl_PLUS_1__q10,
	       gatherInFifos_2_enqP_rl_PLUS_1__q9,
	       n__read__h20132,
	       n__read__h20499,
	       n__read__h20866,
	       upd__h11714,
	       upd__h13889,
	       upd__h20185,
	       upd__h20552,
	       upd__h20919,
	       upd__h9539,
	       x__h16831,
	       x__h16833,
	       x__h17261,
	       x__h17263,
	       x__h17691,
	       x__h17693,
	       y__h16832,
	       y__h17262,
	       y__h17692,
	       y__h20237,
	       y__h20604,
	       y__h20971;
  wire [1 : 0] cnt1__h4934,
	       cnt1__h8233,
	       gatherOutFifo_deqP_rl_PLUS_1__q4,
	       gatherOutFifo_enqP_rl_PLUS_1__q3,
	       n__read__h15361,
	       n__read__h21213,
	       scatterFifo_deqP_rl_PLUS_1__q2,
	       scatterFifo_enqP_rl_PLUS_1__q1,
	       upd__h15489,
	       upd__h21266,
	       upd__h4888,
	       upd__h8187;
  wire IF_IF_IF_gatherInFifos_1_enqP_dummy2_0_34_AND__ETC___d183,
       IF_IF_gatherInFifos_2_enqP_dummy2_0_52_AND_gat_ETC___d182,
       IF_isSent_lat_1_whas_THEN_isSent_lat_1_wget_EL_ETC___d9;

  // action method gatherInPort_0_putFlit
  assign RDY_gatherInPort_0_putFlit = cnt1__h10629 < 3'd2 ;

  // action method gatherInPort_1_putFlit
  assign RDY_gatherInPort_1_putFlit = cnt1__h12804 < 3'd2 ;

  // action method gatherInPort_2_putFlit
  assign RDY_gatherInPort_2_putFlit = cnt1__h14979 < 3'd2 ;

  // actionvalue method gatherOutPort_getFlit
  assign gatherOutPort_getFlit =
	     gatherOutFifo_data_0_lat_0$whas ?
	       gatherOutFifo_data_0_lat_0$wget :
	       gatherOutFifo_data_0_rl ;
  assign RDY_gatherOutPort_getFlit = cnt1__h8233 != 2'd0 ;

  // action method scatterInPort_putFlit
  assign RDY_scatterInPort_putFlit =
	     ((scatterFifo_enqP_rl < scatterFifo_deqP_rl) ?
		2'd1 :
		scatterFifo_enqP_rl - scatterFifo_deqP_rl) ==
	     2'd0 ;

  // actionvalue method scatterOutPort_0_getFlit
  assign scatterOutPort_0_getFlit = scatterOutPort_1_getFlit ;
  assign RDY_scatterOutPort_0_getFlit =
	     cnt1__h4934 != 2'd0 && controlSignal[1] ;

  // actionvalue method scatterOutPort_1_getFlit
  assign scatterOutPort_1_getFlit =
	     EN_scatterInPort_putFlit ?
	       scatterInPort_putFlit_flit :
	       scatterFifo_data_0_rl ;
  assign RDY_scatterOutPort_1_getFlit =
	     cnt1__h4934 != 2'd0 && controlSignal[0] ;

  // action method configureSwitch
  assign RDY_configureSwitch = 1'd1 ;

  // rule RL_sendGatherFlit
  assign WILL_FIRE_RL_sendGatherFlit =
	     (cnt0__h10628 == 3'd0) ?
	       IF_IF_IF_gatherInFifos_1_enqP_dummy2_0_34_AND__ETC___d183 :
	       ((gatherOutFifo_enqP_rl < gatherOutFifo_deqP_rl) ?
		  2'd1 :
		  gatherOutFifo_enqP_rl - gatherOutFifo_deqP_rl) ==
	       2'd0 ;

  // inlined wires
  assign isSent_lat_2$whas =
	     cnt1__h4934 != 2'd0 &&
	     IF_isSent_lat_1_whas_THEN_isSent_lat_1_wget_EL_ETC___d9 ;
  assign gatherOutFifo_data_0_lat_0$wget =
	     (cnt0__h10628 == 3'd0) ?
	       ((cnt0__h12803 == 3'd0) ?
		  SEL_ARR_gatherInFifos_2_data_0_93_BITS_90_TO_8_ETC___d212 :
		  SEL_ARR_gatherInFifos_1_data_0_13_BITS_90_TO_8_ETC___d232) :
	       SEL_ARR_gatherInFifos_0_data_0_34_BITS_90_TO_8_ETC___d253 ;
  assign gatherOutFifo_data_0_lat_0$whas =
	     WILL_FIRE_RL_sendGatherFlit &&
	     (cnt0__h14978 != 3'd0 || cnt0__h12803 != 3'd0 ||
	      cnt0__h10628 != 3'd0) ;
  assign gatherInFifos_0_deqP_lat_0$whas =
	     WILL_FIRE_RL_sendGatherFlit && cnt0__h10628 != 3'd0 ;
  assign gatherInFifos_1_deqP_lat_0$whas =
	     WILL_FIRE_RL_sendGatherFlit && cnt0__h10628 == 3'd0 &&
	     cnt0__h12803 != 3'd0 ;
  assign gatherInFifos_2_deqP_lat_0$whas =
	     WILL_FIRE_RL_sendGatherFlit && cnt0__h10628 == 3'd0 &&
	     cnt0__h12803 == 3'd0 &&
	     cnt0__h14978 != 3'd0 ;

  // register controlSignal
  assign controlSignal$D_IN = configureSwitch_newControlSignal ;
  assign controlSignal$EN = EN_configureSwitch ;

  // register gatherInFifos_0_data_0
  assign gatherInFifos_0_data_0$D_IN = gatherInPort_0_putFlit_flit ;
  assign gatherInFifos_0_data_0$EN =
	     EN_gatherInPort_0_putFlit && x__h16833 == 3'd0 ;

  // register gatherInFifos_0_data_1
  assign gatherInFifos_0_data_1$D_IN = gatherInPort_0_putFlit_flit ;
  assign gatherInFifos_0_data_1$EN =
	     EN_gatherInPort_0_putFlit && x__h16833 == 3'd1 ;

  // register gatherInFifos_0_deqP_dummy2_0
  assign gatherInFifos_0_deqP_dummy2_0$D_IN = 1'd1 ;
  assign gatherInFifos_0_deqP_dummy2_0$EN = gatherInFifos_0_deqP_lat_0$whas ;

  // register gatherInFifos_0_deqP_dummy2_1
  assign gatherInFifos_0_deqP_dummy2_1$D_IN = 1'b0 ;
  assign gatherInFifos_0_deqP_dummy2_1$EN = 1'b0 ;

  // register gatherInFifos_0_deqP_rl
  assign gatherInFifos_0_deqP_rl$D_IN = n__read__h20132 ;
  assign gatherInFifos_0_deqP_rl$EN = 1'd1 ;

  // register gatherInFifos_0_enqP_dummy2_0
  assign gatherInFifos_0_enqP_dummy2_0$D_IN = 1'd1 ;
  assign gatherInFifos_0_enqP_dummy2_0$EN = EN_gatherInPort_0_putFlit ;

  // register gatherInFifos_0_enqP_dummy2_1
  assign gatherInFifos_0_enqP_dummy2_1$D_IN = 1'b0 ;
  assign gatherInFifos_0_enqP_dummy2_1$EN = 1'b0 ;

  // register gatherInFifos_0_enqP_rl
  assign gatherInFifos_0_enqP_rl$D_IN =
	     EN_gatherInPort_0_putFlit ?
	       upd__h9539 :
	       gatherInFifos_0_enqP_rl ;
  assign gatherInFifos_0_enqP_rl$EN = 1'd1 ;

  // register gatherInFifos_1_data_0
  assign gatherInFifos_1_data_0$D_IN = gatherInPort_1_putFlit_flit ;
  assign gatherInFifos_1_data_0$EN =
	     EN_gatherInPort_1_putFlit && x__h17263 == 3'd0 ;

  // register gatherInFifos_1_data_1
  assign gatherInFifos_1_data_1$D_IN = gatherInPort_1_putFlit_flit ;
  assign gatherInFifos_1_data_1$EN =
	     EN_gatherInPort_1_putFlit && x__h17263 == 3'd1 ;

  // register gatherInFifos_1_deqP_dummy2_0
  assign gatherInFifos_1_deqP_dummy2_0$D_IN = 1'd1 ;
  assign gatherInFifos_1_deqP_dummy2_0$EN = gatherInFifos_1_deqP_lat_0$whas ;

  // register gatherInFifos_1_deqP_dummy2_1
  assign gatherInFifos_1_deqP_dummy2_1$D_IN = 1'b0 ;
  assign gatherInFifos_1_deqP_dummy2_1$EN = 1'b0 ;

  // register gatherInFifos_1_deqP_rl
  assign gatherInFifos_1_deqP_rl$D_IN = n__read__h20499 ;
  assign gatherInFifos_1_deqP_rl$EN = 1'd1 ;

  // register gatherInFifos_1_enqP_dummy2_0
  assign gatherInFifos_1_enqP_dummy2_0$D_IN = 1'd1 ;
  assign gatherInFifos_1_enqP_dummy2_0$EN = EN_gatherInPort_1_putFlit ;

  // register gatherInFifos_1_enqP_dummy2_1
  assign gatherInFifos_1_enqP_dummy2_1$D_IN = 1'b0 ;
  assign gatherInFifos_1_enqP_dummy2_1$EN = 1'b0 ;

  // register gatherInFifos_1_enqP_rl
  assign gatherInFifos_1_enqP_rl$D_IN =
	     EN_gatherInPort_1_putFlit ?
	       upd__h11714 :
	       gatherInFifos_1_enqP_rl ;
  assign gatherInFifos_1_enqP_rl$EN = 1'd1 ;

  // register gatherInFifos_2_data_0
  assign gatherInFifos_2_data_0$D_IN = gatherInPort_2_putFlit_flit ;
  assign gatherInFifos_2_data_0$EN =
	     EN_gatherInPort_2_putFlit && x__h17693 == 3'd0 ;

  // register gatherInFifos_2_data_1
  assign gatherInFifos_2_data_1$D_IN = gatherInPort_2_putFlit_flit ;
  assign gatherInFifos_2_data_1$EN =
	     EN_gatherInPort_2_putFlit && x__h17693 == 3'd1 ;

  // register gatherInFifos_2_deqP_dummy2_0
  assign gatherInFifos_2_deqP_dummy2_0$D_IN = 1'd1 ;
  assign gatherInFifos_2_deqP_dummy2_0$EN = gatherInFifos_2_deqP_lat_0$whas ;

  // register gatherInFifos_2_deqP_dummy2_1
  assign gatherInFifos_2_deqP_dummy2_1$D_IN = 1'b0 ;
  assign gatherInFifos_2_deqP_dummy2_1$EN = 1'b0 ;

  // register gatherInFifos_2_deqP_rl
  assign gatherInFifos_2_deqP_rl$D_IN = n__read__h20866 ;
  assign gatherInFifos_2_deqP_rl$EN = 1'd1 ;

  // register gatherInFifos_2_enqP_dummy2_0
  assign gatherInFifos_2_enqP_dummy2_0$D_IN = 1'd1 ;
  assign gatherInFifos_2_enqP_dummy2_0$EN = EN_gatherInPort_2_putFlit ;

  // register gatherInFifos_2_enqP_dummy2_1
  assign gatherInFifos_2_enqP_dummy2_1$D_IN = 1'b0 ;
  assign gatherInFifos_2_enqP_dummy2_1$EN = 1'b0 ;

  // register gatherInFifos_2_enqP_rl
  assign gatherInFifos_2_enqP_rl$D_IN =
	     EN_gatherInPort_2_putFlit ?
	       upd__h13889 :
	       gatherInFifos_2_enqP_rl ;
  assign gatherInFifos_2_enqP_rl$EN = 1'd1 ;

  // register gatherOutFifo_data_0_dummy2_0
  assign gatherOutFifo_data_0_dummy2_0$D_IN = 1'd1 ;
  assign gatherOutFifo_data_0_dummy2_0$EN = gatherOutFifo_data_0_lat_0$whas ;

  // register gatherOutFifo_data_0_dummy2_1
  assign gatherOutFifo_data_0_dummy2_1$D_IN = 1'b0 ;
  assign gatherOutFifo_data_0_dummy2_1$EN = 1'b0 ;

  // register gatherOutFifo_data_0_rl
  assign gatherOutFifo_data_0_rl$D_IN =
	     gatherOutFifo_data_0_lat_0$whas ?
	       gatherOutFifo_data_0_lat_0$wget :
	       gatherOutFifo_data_0_rl ;
  assign gatherOutFifo_data_0_rl$EN = 1'd1 ;

  // register gatherOutFifo_deqP_dummy2_0
  assign gatherOutFifo_deqP_dummy2_0$D_IN = 1'd1 ;
  assign gatherOutFifo_deqP_dummy2_0$EN = EN_gatherOutPort_getFlit ;

  // register gatherOutFifo_deqP_dummy2_1
  assign gatherOutFifo_deqP_dummy2_1$D_IN = 1'b0 ;
  assign gatherOutFifo_deqP_dummy2_1$EN = 1'b0 ;

  // register gatherOutFifo_deqP_rl
  assign gatherOutFifo_deqP_rl$D_IN =
	     EN_gatherOutPort_getFlit ? upd__h8187 : gatherOutFifo_deqP_rl ;
  assign gatherOutFifo_deqP_rl$EN = 1'd1 ;

  // register gatherOutFifo_enqP_dummy2_0
  assign gatherOutFifo_enqP_dummy2_0$D_IN = 1'd1 ;
  assign gatherOutFifo_enqP_dummy2_0$EN = gatherOutFifo_data_0_lat_0$whas ;

  // register gatherOutFifo_enqP_dummy2_1
  assign gatherOutFifo_enqP_dummy2_1$D_IN = 1'b0 ;
  assign gatherOutFifo_enqP_dummy2_1$EN = 1'b0 ;

  // register gatherOutFifo_enqP_rl
  assign gatherOutFifo_enqP_rl$D_IN = n__read__h21213 ;
  assign gatherOutFifo_enqP_rl$EN = 1'd1 ;

  // register isSent_dummy2_0
  assign isSent_dummy2_0$D_IN = 1'd1 ;
  assign isSent_dummy2_0$EN = EN_scatterOutPort_0_getFlit ;

  // register isSent_dummy2_1
  assign isSent_dummy2_1$D_IN = 1'd1 ;
  assign isSent_dummy2_1$EN = EN_scatterOutPort_1_getFlit ;

  // register isSent_dummy2_2
  assign isSent_dummy2_2$D_IN = 1'd1 ;
  assign isSent_dummy2_2$EN = isSent_lat_2$whas ;

  // register isSent_rl
  assign isSent_rl$D_IN =
	     !isSent_lat_2$whas &&
	     IF_isSent_lat_1_whas_THEN_isSent_lat_1_wget_EL_ETC___d9 ;
  assign isSent_rl$EN = 1'd1 ;

  // register scatterFifo_data_0_dummy2_0
  assign scatterFifo_data_0_dummy2_0$D_IN = 1'd1 ;
  assign scatterFifo_data_0_dummy2_0$EN = EN_scatterInPort_putFlit ;

  // register scatterFifo_data_0_dummy2_1
  assign scatterFifo_data_0_dummy2_1$D_IN = 1'b0 ;
  assign scatterFifo_data_0_dummy2_1$EN = 1'b0 ;

  // register scatterFifo_data_0_rl
  assign scatterFifo_data_0_rl$D_IN = scatterOutPort_1_getFlit ;
  assign scatterFifo_data_0_rl$EN = 1'd1 ;

  // register scatterFifo_deqP_dummy2_0
  assign scatterFifo_deqP_dummy2_0$D_IN = 1'd1 ;
  assign scatterFifo_deqP_dummy2_0$EN = isSent_lat_2$whas ;

  // register scatterFifo_deqP_dummy2_1
  assign scatterFifo_deqP_dummy2_1$D_IN = 1'b0 ;
  assign scatterFifo_deqP_dummy2_1$EN = 1'b0 ;

  // register scatterFifo_deqP_rl
  assign scatterFifo_deqP_rl$D_IN =
	     isSent_lat_2$whas ? upd__h4888 : scatterFifo_deqP_rl ;
  assign scatterFifo_deqP_rl$EN = 1'd1 ;

  // register scatterFifo_enqP_dummy2_0
  assign scatterFifo_enqP_dummy2_0$D_IN = 1'd1 ;
  assign scatterFifo_enqP_dummy2_0$EN = EN_scatterInPort_putFlit ;

  // register scatterFifo_enqP_dummy2_1
  assign scatterFifo_enqP_dummy2_1$D_IN = 1'b0 ;
  assign scatterFifo_enqP_dummy2_1$EN = 1'b0 ;

  // register scatterFifo_enqP_rl
  assign scatterFifo_enqP_rl$D_IN = n__read__h15361 ;
  assign scatterFifo_enqP_rl$EN = 1'd1 ;

  // remaining internal signals
  assign IF_IF_IF_gatherInFifos_1_enqP_dummy2_0_34_AND__ETC___d183 =
	     (cnt0__h12803 == 3'd0) ?
	       IF_IF_gatherInFifos_2_enqP_dummy2_0_52_AND_gat_ETC___d182 :
	       ((gatherOutFifo_enqP_rl < gatherOutFifo_deqP_rl) ?
		  2'd1 :
		  gatherOutFifo_enqP_rl - gatherOutFifo_deqP_rl) ==
	       2'd0 ;
  assign IF_IF_gatherInFifos_2_enqP_dummy2_0_52_AND_gat_ETC___d182 =
	     cnt0__h14978 == 3'd0 ||
	     ((gatherOutFifo_enqP_rl < gatherOutFifo_deqP_rl) ?
		2'd1 :
		gatherOutFifo_enqP_rl - gatherOutFifo_deqP_rl) ==
	     2'd0 ;
  assign IF_isSent_lat_1_whas_THEN_isSent_lat_1_wget_EL_ETC___d9 =
	     EN_scatterOutPort_1_getFlit || EN_scatterOutPort_0_getFlit ||
	     isSent_rl ;
  assign SEL_ARR_gatherInFifos_0_data_0_34_BITS_90_TO_8_ETC___d253 =
	     { CASE_y6832_0_gatherInFifos_0_data_0_BITS_90_TO_ETC__q19,
	       CASE_y6832_0_gatherInFifos_0_data_0_BITS_87_TO_ETC__q20,
	       CASE_y6832_0_gatherInFifos_0_data_0_BITS_22_TO_ETC__q21,
	       CASE_y6832_0_gatherInFifos_0_data_0_BITS_15_TO_ETC__q22 } ;
  assign SEL_ARR_gatherInFifos_1_data_0_13_BITS_90_TO_8_ETC___d232 =
	     { CASE_y7262_0_gatherInFifos_1_data_0_BITS_90_TO_ETC__q15,
	       CASE_y7262_0_gatherInFifos_1_data_0_BITS_87_TO_ETC__q16,
	       CASE_y7262_0_gatherInFifos_1_data_0_BITS_22_TO_ETC__q17,
	       CASE_y7262_0_gatherInFifos_1_data_0_BITS_15_TO_ETC__q18 } ;
  assign SEL_ARR_gatherInFifos_2_data_0_93_BITS_90_TO_8_ETC___d212 =
	     { CASE_y7692_0_gatherInFifos_2_data_0_BITS_90_TO_ETC__q11,
	       CASE_y7692_0_gatherInFifos_2_data_0_BITS_87_TO_ETC__q12,
	       CASE_y7692_0_gatherInFifos_2_data_0_BITS_22_TO_ETC__q13,
	       CASE_y7692_0_gatherInFifos_2_data_0_BITS_15_TO_ETC__q14 } ;
  assign cnt0__h10628 =
	     (gatherInFifos_0_enqP_rl < gatherInFifos_0_deqP_rl) ?
	       x__h16831 - y__h16832 :
	       gatherInFifos_0_enqP_rl - gatherInFifos_0_deqP_rl ;
  assign cnt0__h12803 =
	     (gatherInFifos_1_enqP_rl < gatherInFifos_1_deqP_rl) ?
	       x__h17261 - y__h17262 :
	       gatherInFifos_1_enqP_rl - gatherInFifos_1_deqP_rl ;
  assign cnt0__h14978 =
	     (gatherInFifos_2_enqP_rl < gatherInFifos_2_deqP_rl) ?
	       x__h17691 - y__h17692 :
	       gatherInFifos_2_enqP_rl - gatherInFifos_2_deqP_rl ;
  assign cnt1__h10629 =
	     (gatherInFifos_0_enqP_rl < n__read__h20132) ?
	       x__h16831 - y__h20237 :
	       gatherInFifos_0_enqP_rl - n__read__h20132 ;
  assign cnt1__h12804 =
	     (gatherInFifos_1_enqP_rl < n__read__h20499) ?
	       x__h17261 - y__h20604 :
	       gatherInFifos_1_enqP_rl - n__read__h20499 ;
  assign cnt1__h14979 =
	     (gatherInFifos_2_enqP_rl < n__read__h20866) ?
	       x__h17691 - y__h20971 :
	       gatherInFifos_2_enqP_rl - n__read__h20866 ;
  assign cnt1__h4934 =
	     (n__read__h15361 < scatterFifo_deqP_rl) ?
	       2'd1 :
	       n__read__h15361 - scatterFifo_deqP_rl ;
  assign cnt1__h8233 =
	     (n__read__h21213 < gatherOutFifo_deqP_rl) ?
	       2'd1 :
	       n__read__h21213 - gatherOutFifo_deqP_rl ;
  assign gatherInFifos_0_deqP_rl_PLUS_1__q6 = gatherInFifos_0_deqP_rl + 3'd1 ;
  assign gatherInFifos_0_enqP_rl_PLUS_1__q5 = gatherInFifos_0_enqP_rl + 3'd1 ;
  assign gatherInFifos_1_deqP_rl_PLUS_1__q8 = gatherInFifos_1_deqP_rl + 3'd1 ;
  assign gatherInFifos_1_enqP_rl_PLUS_1__q7 = gatherInFifos_1_enqP_rl + 3'd1 ;
  assign gatherInFifos_2_deqP_rl_PLUS_1__q10 =
	     gatherInFifos_2_deqP_rl + 3'd1 ;
  assign gatherInFifos_2_enqP_rl_PLUS_1__q9 = gatherInFifos_2_enqP_rl + 3'd1 ;
  assign gatherOutFifo_deqP_rl_PLUS_1__q4 = gatherOutFifo_deqP_rl + 2'd1 ;
  assign gatherOutFifo_enqP_rl_PLUS_1__q3 = gatherOutFifo_enqP_rl + 2'd1 ;
  assign n__read__h15361 =
	     EN_scatterInPort_putFlit ? upd__h15489 : scatterFifo_enqP_rl ;
  assign n__read__h20132 =
	     gatherInFifos_0_deqP_lat_0$whas ?
	       upd__h20185 :
	       gatherInFifos_0_deqP_rl ;
  assign n__read__h20499 =
	     gatherInFifos_1_deqP_lat_0$whas ?
	       upd__h20552 :
	       gatherInFifos_1_deqP_rl ;
  assign n__read__h20866 =
	     gatherInFifos_2_deqP_lat_0$whas ?
	       upd__h20919 :
	       gatherInFifos_2_deqP_rl ;
  assign n__read__h21213 =
	     gatherOutFifo_data_0_lat_0$whas ?
	       upd__h21266 :
	       gatherOutFifo_enqP_rl ;
  assign scatterFifo_deqP_rl_PLUS_1__q2 = scatterFifo_deqP_rl + 2'd1 ;
  assign scatterFifo_enqP_rl_PLUS_1__q1 = scatterFifo_enqP_rl + 2'd1 ;
  assign upd__h11714 = { 1'd0, gatherInFifos_1_enqP_rl_PLUS_1__q7[1:0] } ;
  assign upd__h13889 = { 1'd0, gatherInFifos_2_enqP_rl_PLUS_1__q9[1:0] } ;
  assign upd__h15489 = { 1'd0, scatterFifo_enqP_rl_PLUS_1__q1[0] } ;
  assign upd__h20185 = { 1'd0, gatherInFifos_0_deqP_rl_PLUS_1__q6[1:0] } ;
  assign upd__h20552 = { 1'd0, gatherInFifos_1_deqP_rl_PLUS_1__q8[1:0] } ;
  assign upd__h20919 = { 1'd0, gatherInFifos_2_deqP_rl_PLUS_1__q10[1:0] } ;
  assign upd__h21266 = { 1'd0, gatherOutFifo_enqP_rl_PLUS_1__q3[0] } ;
  assign upd__h4888 = { 1'd0, scatterFifo_deqP_rl_PLUS_1__q2[0] } ;
  assign upd__h8187 = { 1'd0, gatherOutFifo_deqP_rl_PLUS_1__q4[0] } ;
  assign upd__h9539 = { 1'd0, gatherInFifos_0_enqP_rl_PLUS_1__q5[1:0] } ;
  assign x__h16831 = x__h16833 + 3'd2 ;
  assign x__h16833 = { 2'd0, gatherInFifos_0_enqP_rl[0] } ;
  assign x__h17261 = x__h17263 + 3'd2 ;
  assign x__h17263 = { 2'd0, gatherInFifos_1_enqP_rl[0] } ;
  assign x__h17691 = x__h17693 + 3'd2 ;
  assign x__h17693 = { 2'd0, gatherInFifos_2_enqP_rl[0] } ;
  assign y__h16832 = { 2'd0, gatherInFifos_0_deqP_rl[0] } ;
  assign y__h17262 = { 2'd0, gatherInFifos_1_deqP_rl[0] } ;
  assign y__h17692 = { 2'd0, gatherInFifos_2_deqP_rl[0] } ;
  assign y__h20237 = { 2'd0, n__read__h20132[0] } ;
  assign y__h20604 = { 2'd0, n__read__h20499[0] } ;
  assign y__h20971 = { 2'd0, n__read__h20866[0] } ;
  always@(y__h17692 or gatherInFifos_2_data_0 or gatherInFifos_2_data_1)
  begin
    case (y__h17692)
      3'd0:
	  CASE_y7692_0_gatherInFifos_2_data_0_BITS_90_TO_ETC__q11 =
	      gatherInFifos_2_data_0[90:88];
      3'd1:
	  CASE_y7692_0_gatherInFifos_2_data_0_BITS_90_TO_ETC__q11 =
	      gatherInFifos_2_data_1[90:88];
      default: CASE_y7692_0_gatherInFifos_2_data_0_BITS_90_TO_ETC__q11 =
		   3'b010 /* unspecified value */ ;
    endcase
  end
  always@(y__h17692 or gatherInFifos_2_data_0 or gatherInFifos_2_data_1)
  begin
    case (y__h17692)
      3'd0:
	  CASE_y7692_0_gatherInFifos_2_data_0_BITS_87_TO_ETC__q12 =
	      gatherInFifos_2_data_0[87:23];
      3'd1:
	  CASE_y7692_0_gatherInFifos_2_data_0_BITS_87_TO_ETC__q12 =
	      gatherInFifos_2_data_1[87:23];
      default: CASE_y7692_0_gatherInFifos_2_data_0_BITS_87_TO_ETC__q12 =
		   65'h0AAAAAAAAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  always@(y__h17692 or gatherInFifos_2_data_0 or gatherInFifos_2_data_1)
  begin
    case (y__h17692)
      3'd0:
	  CASE_y7692_0_gatherInFifos_2_data_0_BITS_22_TO_ETC__q13 =
	      gatherInFifos_2_data_0[22:16];
      3'd1:
	  CASE_y7692_0_gatherInFifos_2_data_0_BITS_22_TO_ETC__q13 =
	      gatherInFifos_2_data_1[22:16];
      default: CASE_y7692_0_gatherInFifos_2_data_0_BITS_22_TO_ETC__q13 =
		   7'b0101010 /* unspecified value */ ;
    endcase
  end
  always@(y__h17692 or gatherInFifos_2_data_0 or gatherInFifos_2_data_1)
  begin
    case (y__h17692)
      3'd0:
	  CASE_y7692_0_gatherInFifos_2_data_0_BITS_15_TO_ETC__q14 =
	      gatherInFifos_2_data_0[15:0];
      3'd1:
	  CASE_y7692_0_gatherInFifos_2_data_0_BITS_15_TO_ETC__q14 =
	      gatherInFifos_2_data_1[15:0];
      default: CASE_y7692_0_gatherInFifos_2_data_0_BITS_15_TO_ETC__q14 =
		   16'b1010101010101010 /* unspecified value */ ;
    endcase
  end
  always@(y__h17262 or gatherInFifos_1_data_0 or gatherInFifos_1_data_1)
  begin
    case (y__h17262)
      3'd0:
	  CASE_y7262_0_gatherInFifos_1_data_0_BITS_90_TO_ETC__q15 =
	      gatherInFifos_1_data_0[90:88];
      3'd1:
	  CASE_y7262_0_gatherInFifos_1_data_0_BITS_90_TO_ETC__q15 =
	      gatherInFifos_1_data_1[90:88];
      default: CASE_y7262_0_gatherInFifos_1_data_0_BITS_90_TO_ETC__q15 =
		   3'b010 /* unspecified value */ ;
    endcase
  end
  always@(y__h17262 or gatherInFifos_1_data_0 or gatherInFifos_1_data_1)
  begin
    case (y__h17262)
      3'd0:
	  CASE_y7262_0_gatherInFifos_1_data_0_BITS_87_TO_ETC__q16 =
	      gatherInFifos_1_data_0[87:23];
      3'd1:
	  CASE_y7262_0_gatherInFifos_1_data_0_BITS_87_TO_ETC__q16 =
	      gatherInFifos_1_data_1[87:23];
      default: CASE_y7262_0_gatherInFifos_1_data_0_BITS_87_TO_ETC__q16 =
		   65'h0AAAAAAAAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  always@(y__h17262 or gatherInFifos_1_data_0 or gatherInFifos_1_data_1)
  begin
    case (y__h17262)
      3'd0:
	  CASE_y7262_0_gatherInFifos_1_data_0_BITS_22_TO_ETC__q17 =
	      gatherInFifos_1_data_0[22:16];
      3'd1:
	  CASE_y7262_0_gatherInFifos_1_data_0_BITS_22_TO_ETC__q17 =
	      gatherInFifos_1_data_1[22:16];
      default: CASE_y7262_0_gatherInFifos_1_data_0_BITS_22_TO_ETC__q17 =
		   7'b0101010 /* unspecified value */ ;
    endcase
  end
  always@(y__h17262 or gatherInFifos_1_data_0 or gatherInFifos_1_data_1)
  begin
    case (y__h17262)
      3'd0:
	  CASE_y7262_0_gatherInFifos_1_data_0_BITS_15_TO_ETC__q18 =
	      gatherInFifos_1_data_0[15:0];
      3'd1:
	  CASE_y7262_0_gatherInFifos_1_data_0_BITS_15_TO_ETC__q18 =
	      gatherInFifos_1_data_1[15:0];
      default: CASE_y7262_0_gatherInFifos_1_data_0_BITS_15_TO_ETC__q18 =
		   16'b1010101010101010 /* unspecified value */ ;
    endcase
  end
  always@(y__h16832 or gatherInFifos_0_data_0 or gatherInFifos_0_data_1)
  begin
    case (y__h16832)
      3'd0:
	  CASE_y6832_0_gatherInFifos_0_data_0_BITS_90_TO_ETC__q19 =
	      gatherInFifos_0_data_0[90:88];
      3'd1:
	  CASE_y6832_0_gatherInFifos_0_data_0_BITS_90_TO_ETC__q19 =
	      gatherInFifos_0_data_1[90:88];
      default: CASE_y6832_0_gatherInFifos_0_data_0_BITS_90_TO_ETC__q19 =
		   3'b010 /* unspecified value */ ;
    endcase
  end
  always@(y__h16832 or gatherInFifos_0_data_0 or gatherInFifos_0_data_1)
  begin
    case (y__h16832)
      3'd0:
	  CASE_y6832_0_gatherInFifos_0_data_0_BITS_87_TO_ETC__q20 =
	      gatherInFifos_0_data_0[87:23];
      3'd1:
	  CASE_y6832_0_gatherInFifos_0_data_0_BITS_87_TO_ETC__q20 =
	      gatherInFifos_0_data_1[87:23];
      default: CASE_y6832_0_gatherInFifos_0_data_0_BITS_87_TO_ETC__q20 =
		   65'h0AAAAAAAAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  always@(y__h16832 or gatherInFifos_0_data_0 or gatherInFifos_0_data_1)
  begin
    case (y__h16832)
      3'd0:
	  CASE_y6832_0_gatherInFifos_0_data_0_BITS_22_TO_ETC__q21 =
	      gatherInFifos_0_data_0[22:16];
      3'd1:
	  CASE_y6832_0_gatherInFifos_0_data_0_BITS_22_TO_ETC__q21 =
	      gatherInFifos_0_data_1[22:16];
      default: CASE_y6832_0_gatherInFifos_0_data_0_BITS_22_TO_ETC__q21 =
		   7'b0101010 /* unspecified value */ ;
    endcase
  end
  always@(y__h16832 or gatherInFifos_0_data_0 or gatherInFifos_0_data_1)
  begin
    case (y__h16832)
      3'd0:
	  CASE_y6832_0_gatherInFifos_0_data_0_BITS_15_TO_ETC__q22 =
	      gatherInFifos_0_data_0[15:0];
      3'd1:
	  CASE_y6832_0_gatherInFifos_0_data_0_BITS_15_TO_ETC__q22 =
	      gatherInFifos_0_data_1[15:0];
      default: CASE_y6832_0_gatherInFifos_0_data_0_BITS_15_TO_ETC__q22 =
		   16'b1010101010101010 /* unspecified value */ ;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        controlSignal <= `BSV_ASSIGNMENT_DELAY 2'd0;
	gatherInFifos_0_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherInFifos_0_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherInFifos_0_deqP_rl <= `BSV_ASSIGNMENT_DELAY 3'd0;
	gatherInFifos_0_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherInFifos_0_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherInFifos_0_enqP_rl <= `BSV_ASSIGNMENT_DELAY 3'd0;
	gatherInFifos_1_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherInFifos_1_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherInFifos_1_deqP_rl <= `BSV_ASSIGNMENT_DELAY 3'd0;
	gatherInFifos_1_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherInFifos_1_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherInFifos_1_enqP_rl <= `BSV_ASSIGNMENT_DELAY 3'd0;
	gatherInFifos_2_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherInFifos_2_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherInFifos_2_deqP_rl <= `BSV_ASSIGNMENT_DELAY 3'd0;
	gatherInFifos_2_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherInFifos_2_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherInFifos_2_enqP_rl <= `BSV_ASSIGNMENT_DELAY 3'd0;
	gatherOutFifo_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherOutFifo_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherOutFifo_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	    91'h2AAAAAAAAAAAAAAAAAAAAAA;
	gatherOutFifo_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherOutFifo_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherOutFifo_deqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	gatherOutFifo_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherOutFifo_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	gatherOutFifo_enqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	isSent_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	isSent_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	isSent_dummy2_2 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	isSent_rl <= `BSV_ASSIGNMENT_DELAY 1'd0;
	scatterFifo_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFifo_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFifo_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	    91'h2AAAAAAAAAAAAAAAAAAAAAA;
	scatterFifo_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFifo_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFifo_deqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	scatterFifo_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFifo_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	scatterFifo_enqP_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
      end
    else
      begin
        if (controlSignal$EN)
	  controlSignal <= `BSV_ASSIGNMENT_DELAY controlSignal$D_IN;
	if (gatherInFifos_0_deqP_dummy2_0$EN)
	  gatherInFifos_0_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_0_deqP_dummy2_0$D_IN;
	if (gatherInFifos_0_deqP_dummy2_1$EN)
	  gatherInFifos_0_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_0_deqP_dummy2_1$D_IN;
	if (gatherInFifos_0_deqP_rl$EN)
	  gatherInFifos_0_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_0_deqP_rl$D_IN;
	if (gatherInFifos_0_enqP_dummy2_0$EN)
	  gatherInFifos_0_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_0_enqP_dummy2_0$D_IN;
	if (gatherInFifos_0_enqP_dummy2_1$EN)
	  gatherInFifos_0_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_0_enqP_dummy2_1$D_IN;
	if (gatherInFifos_0_enqP_rl$EN)
	  gatherInFifos_0_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_0_enqP_rl$D_IN;
	if (gatherInFifos_1_deqP_dummy2_0$EN)
	  gatherInFifos_1_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_1_deqP_dummy2_0$D_IN;
	if (gatherInFifos_1_deqP_dummy2_1$EN)
	  gatherInFifos_1_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_1_deqP_dummy2_1$D_IN;
	if (gatherInFifos_1_deqP_rl$EN)
	  gatherInFifos_1_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_1_deqP_rl$D_IN;
	if (gatherInFifos_1_enqP_dummy2_0$EN)
	  gatherInFifos_1_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_1_enqP_dummy2_0$D_IN;
	if (gatherInFifos_1_enqP_dummy2_1$EN)
	  gatherInFifos_1_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_1_enqP_dummy2_1$D_IN;
	if (gatherInFifos_1_enqP_rl$EN)
	  gatherInFifos_1_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_1_enqP_rl$D_IN;
	if (gatherInFifos_2_deqP_dummy2_0$EN)
	  gatherInFifos_2_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_2_deqP_dummy2_0$D_IN;
	if (gatherInFifos_2_deqP_dummy2_1$EN)
	  gatherInFifos_2_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_2_deqP_dummy2_1$D_IN;
	if (gatherInFifos_2_deqP_rl$EN)
	  gatherInFifos_2_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_2_deqP_rl$D_IN;
	if (gatherInFifos_2_enqP_dummy2_0$EN)
	  gatherInFifos_2_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_2_enqP_dummy2_0$D_IN;
	if (gatherInFifos_2_enqP_dummy2_1$EN)
	  gatherInFifos_2_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_2_enqP_dummy2_1$D_IN;
	if (gatherInFifos_2_enqP_rl$EN)
	  gatherInFifos_2_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      gatherInFifos_2_enqP_rl$D_IN;
	if (gatherOutFifo_data_0_dummy2_0$EN)
	  gatherOutFifo_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      gatherOutFifo_data_0_dummy2_0$D_IN;
	if (gatherOutFifo_data_0_dummy2_1$EN)
	  gatherOutFifo_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      gatherOutFifo_data_0_dummy2_1$D_IN;
	if (gatherOutFifo_data_0_rl$EN)
	  gatherOutFifo_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	      gatherOutFifo_data_0_rl$D_IN;
	if (gatherOutFifo_deqP_dummy2_0$EN)
	  gatherOutFifo_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      gatherOutFifo_deqP_dummy2_0$D_IN;
	if (gatherOutFifo_deqP_dummy2_1$EN)
	  gatherOutFifo_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      gatherOutFifo_deqP_dummy2_1$D_IN;
	if (gatherOutFifo_deqP_rl$EN)
	  gatherOutFifo_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      gatherOutFifo_deqP_rl$D_IN;
	if (gatherOutFifo_enqP_dummy2_0$EN)
	  gatherOutFifo_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      gatherOutFifo_enqP_dummy2_0$D_IN;
	if (gatherOutFifo_enqP_dummy2_1$EN)
	  gatherOutFifo_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      gatherOutFifo_enqP_dummy2_1$D_IN;
	if (gatherOutFifo_enqP_rl$EN)
	  gatherOutFifo_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      gatherOutFifo_enqP_rl$D_IN;
	if (isSent_dummy2_0$EN)
	  isSent_dummy2_0 <= `BSV_ASSIGNMENT_DELAY isSent_dummy2_0$D_IN;
	if (isSent_dummy2_1$EN)
	  isSent_dummy2_1 <= `BSV_ASSIGNMENT_DELAY isSent_dummy2_1$D_IN;
	if (isSent_dummy2_2$EN)
	  isSent_dummy2_2 <= `BSV_ASSIGNMENT_DELAY isSent_dummy2_2$D_IN;
	if (isSent_rl$EN) isSent_rl <= `BSV_ASSIGNMENT_DELAY isSent_rl$D_IN;
	if (scatterFifo_data_0_dummy2_0$EN)
	  scatterFifo_data_0_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      scatterFifo_data_0_dummy2_0$D_IN;
	if (scatterFifo_data_0_dummy2_1$EN)
	  scatterFifo_data_0_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      scatterFifo_data_0_dummy2_1$D_IN;
	if (scatterFifo_data_0_rl$EN)
	  scatterFifo_data_0_rl <= `BSV_ASSIGNMENT_DELAY
	      scatterFifo_data_0_rl$D_IN;
	if (scatterFifo_deqP_dummy2_0$EN)
	  scatterFifo_deqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      scatterFifo_deqP_dummy2_0$D_IN;
	if (scatterFifo_deqP_dummy2_1$EN)
	  scatterFifo_deqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      scatterFifo_deqP_dummy2_1$D_IN;
	if (scatterFifo_deqP_rl$EN)
	  scatterFifo_deqP_rl <= `BSV_ASSIGNMENT_DELAY
	      scatterFifo_deqP_rl$D_IN;
	if (scatterFifo_enqP_dummy2_0$EN)
	  scatterFifo_enqP_dummy2_0 <= `BSV_ASSIGNMENT_DELAY
	      scatterFifo_enqP_dummy2_0$D_IN;
	if (scatterFifo_enqP_dummy2_1$EN)
	  scatterFifo_enqP_dummy2_1 <= `BSV_ASSIGNMENT_DELAY
	      scatterFifo_enqP_dummy2_1$D_IN;
	if (scatterFifo_enqP_rl$EN)
	  scatterFifo_enqP_rl <= `BSV_ASSIGNMENT_DELAY
	      scatterFifo_enqP_rl$D_IN;
      end
    if (gatherInFifos_0_data_0$EN)
      gatherInFifos_0_data_0 <= `BSV_ASSIGNMENT_DELAY
	  gatherInFifos_0_data_0$D_IN;
    if (gatherInFifos_0_data_1$EN)
      gatherInFifos_0_data_1 <= `BSV_ASSIGNMENT_DELAY
	  gatherInFifos_0_data_1$D_IN;
    if (gatherInFifos_1_data_0$EN)
      gatherInFifos_1_data_0 <= `BSV_ASSIGNMENT_DELAY
	  gatherInFifos_1_data_0$D_IN;
    if (gatherInFifos_1_data_1$EN)
      gatherInFifos_1_data_1 <= `BSV_ASSIGNMENT_DELAY
	  gatherInFifos_1_data_1$D_IN;
    if (gatherInFifos_2_data_0$EN)
      gatherInFifos_2_data_0 <= `BSV_ASSIGNMENT_DELAY
	  gatherInFifos_2_data_0$D_IN;
    if (gatherInFifos_2_data_1$EN)
      gatherInFifos_2_data_1 <= `BSV_ASSIGNMENT_DELAY
	  gatherInFifos_2_data_1$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    controlSignal = 2'h2;
    gatherInFifos_0_data_0 = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    gatherInFifos_0_data_1 = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    gatherInFifos_0_deqP_dummy2_0 = 1'h0;
    gatherInFifos_0_deqP_dummy2_1 = 1'h0;
    gatherInFifos_0_deqP_rl = 3'h2;
    gatherInFifos_0_enqP_dummy2_0 = 1'h0;
    gatherInFifos_0_enqP_dummy2_1 = 1'h0;
    gatherInFifos_0_enqP_rl = 3'h2;
    gatherInFifos_1_data_0 = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    gatherInFifos_1_data_1 = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    gatherInFifos_1_deqP_dummy2_0 = 1'h0;
    gatherInFifos_1_deqP_dummy2_1 = 1'h0;
    gatherInFifos_1_deqP_rl = 3'h2;
    gatherInFifos_1_enqP_dummy2_0 = 1'h0;
    gatherInFifos_1_enqP_dummy2_1 = 1'h0;
    gatherInFifos_1_enqP_rl = 3'h2;
    gatherInFifos_2_data_0 = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    gatherInFifos_2_data_1 = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    gatherInFifos_2_deqP_dummy2_0 = 1'h0;
    gatherInFifos_2_deqP_dummy2_1 = 1'h0;
    gatherInFifos_2_deqP_rl = 3'h2;
    gatherInFifos_2_enqP_dummy2_0 = 1'h0;
    gatherInFifos_2_enqP_dummy2_1 = 1'h0;
    gatherInFifos_2_enqP_rl = 3'h2;
    gatherOutFifo_data_0_dummy2_0 = 1'h0;
    gatherOutFifo_data_0_dummy2_1 = 1'h0;
    gatherOutFifo_data_0_rl = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    gatherOutFifo_deqP_dummy2_0 = 1'h0;
    gatherOutFifo_deqP_dummy2_1 = 1'h0;
    gatherOutFifo_deqP_rl = 2'h2;
    gatherOutFifo_enqP_dummy2_0 = 1'h0;
    gatherOutFifo_enqP_dummy2_1 = 1'h0;
    gatherOutFifo_enqP_rl = 2'h2;
    isSent_dummy2_0 = 1'h0;
    isSent_dummy2_1 = 1'h0;
    isSent_dummy2_2 = 1'h0;
    isSent_rl = 1'h0;
    scatterFifo_data_0_dummy2_0 = 1'h0;
    scatterFifo_data_0_dummy2_1 = 1'h0;
    scatterFifo_data_0_rl = 91'h2AAAAAAAAAAAAAAAAAAAAAA;
    scatterFifo_deqP_dummy2_0 = 1'h0;
    scatterFifo_deqP_dummy2_1 = 1'h0;
    scatterFifo_deqP_rl = 2'h2;
    scatterFifo_enqP_dummy2_0 = 1'h0;
    scatterFifo_enqP_dummy2_1 = 1'h0;
    scatterFifo_enqP_rl = 2'h2;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkTopSwitch

